#define ROLE_GNOLL "Gnoll Champion"
#define CAT_GNOLL "gnoll_champions"
#define GNOLL_PACK_LIMIT 5
#define GNOLL_FOUNDER_SLOTS 3
#define GNOLL_RITE_TIME (10 SECONDS)
#define GNOLL_BOND_DURATION (10 MINUTES)
#define GNOLL_BOND_ESCAPE_RANGE 10
#define GNOLL_CUSTOMIZATION_WINDOW (10 MINUTES)
#define GNOLL_FERTILITY_MARK_DURATION (30 MINUTES)
#define GNOLL_RELEASE_REMINDER_INTERVAL (2 MINUTES)
#define GNOLL_STALK_RECOVERY (1 MINUTES)
#define GNOLL_ABDUCT_RECOVERY (20 SECONDS)
#define GNOLL_ABDUCT_DAMAGE_LIMIT 100
#define GNOLL_ABDUCT_BLOOD_COST 75
#define GNOLL_HUNT_BOUND_TIME (30 SECONDS)
#define GNOLL_HUNT_WITNESS_RANGE 7
#define GNOLL_MAX_FAVOR 4
#define GNOLL_FAVOR_KEEN_TRAIL 1
#define GNOLL_FAVOR_SWIFT_PATH 2
#define GNOLL_FAVOR_THICK_PELTS 3
#define GNOLL_FAVOR_RENEWAL 4

