#define DEFEAT_MODE_KO_RUNE "ko_rune"
#define DEFEAT_MODE_KO_ONLY "ko_only"
#define DEFEAT_MODE_NO_RETURN "no_return"
#define DEFEAT_MODE_DEFAULT DEFEAT_MODE_KO_RUNE

#define DEFEAT_REASON_DAMAGE "damage"
#define DEFEAT_REASON_PAIN "pain"
#define DEFEAT_REASON_DEATH "death"
#define DEFEAT_REASON_HAZARD "hazard"
#define DEFEAT_REASON_HORNY "horny"

#define DEFEAT_SEVERITY_LIGHT "light"
#define DEFEAT_SEVERITY_NORMAL "normal"
#define DEFEAT_SEVERITY_SEVERE "severe"

#define DEFEAT_TREATMENT_MEDICAL "medical"
#define DEFEAT_TREATMENT_SPIRITUAL "spiritual"
#define DEFEAT_TREATMENT_UNIVERSAL "universal"

#define DEFEAT_RUNE_MAX_CHARGES 5
#define DEFEAT_RUNE_RECHARGE_TIME (60 MINUTES)
#define DEFEAT_RUNE_SPEND_KIND "kind"
#define DEFEAT_RUNE_CHARGES_REMAINING "charges_remaining"
#define DEFEAT_RUNE_SPEND_FIRST_FREE "first_free"
#define DEFEAT_RUNE_SPEND_CHARGED "charged"
#define DEFEAT_RUNE_SPEND_EMERGENCY "emergency"

#define DEFEAT_DAMAGE_THRESHOLD_DEFAULT 200
#define DEFEAT_SHOCK_WARNING_STAGE SHOCK_STAGE_4
#define DEFEAT_SHOCK_DEFEAT_STAGE SHOCK_STAGE_6
#define DEFEAT_SHOCK_HARD_STAGE SHOCK_STAGE_8
#define DEFEAT_SHOCK_SUSTAIN_DURATION (3 SECONDS)
