#define STOCK_GENERIC "generic"
#define STOCK_FOOD "foods"
#define STOCK_METAL "metals"

//ADD
#define STOCK_FRUIT "Fruit"
#define STOCK_VEGETABLE "Vegetable"
#define STOCK_ANIMAL "Animal"
#define STOCK_SEAFOOD "Seafood"
//ADD -

#define STOCK_CATEGORIES list(STOCK_GENERIC, STOCK_FOOD, STOCK_METAL, STOCK_FRUIT, STOCK_VEGETABLE, STOCK_ANIMAL, STOCK_SEAFOOD)
