// Succubus antagonist defines.

#define IS_SUCCUBUS(mob) (mob?.mind?.has_antag_datum(/datum/antagonist/succubus))

/// Base essence from a first-time partner's climax, before multipliers
#define SUCCUBUS_ESSENCE_BASE_HARVEST 50
/// Each repeat harvest from the same partner multiplies by this...
#define SUCCUBUS_NOVELTY_DECAY 0.4
/// ...but never below this floor
#define SUCCUBUS_NOVELTY_FLOOR 0.1
/// Arousal adds at most 50% to a climax harvest
#define SUCCUBUS_AROUSAL_BONUS_DIVISOR 500
#define SUCCUBUS_AROUSAL_BONUS_MAX 0.5
/// Starting essence cap
#define SUCCUBUS_ESSENCE_CAP_BASE 300
#define SUCCUBUS_ESSENCE_CAP_TIER_2 350
#define SUCCUBUS_ESSENCE_CAP_TIER_3 400
#define SUCCUBUS_ESSENCE_CAP_TIER_4 500
#define SUCCUBUS_CONTRACT_TIER_MAX 4
#define SUCCUBUS_CONTRACT_HIGH_AROUSAL 250
/// Corruption multipliers use the highest applicable value and never compound.
#define SUCCUBUS_CORRUPTION_MARRIED 1.5
#define SUCCUBUS_CORRUPTION_VIRGIN 2
#define SUCCUBUS_CORRUPTION_CLERGY 3
/// Recoverable victim consequences from direct climax harvesting.
#define SUCCUBUS_DEPLETION_SOUL_TOUCHED 1
#define SUCCUBUS_DEPLETION_SOUL_DRAINED 2
#define SUCCUBUS_DEPLETION_HOLLOWED 3
#define SUCCUBUS_DEPLETION_MAX_STAGE SUCCUBUS_DEPLETION_HOLLOWED
#define SUCCUBUS_DEPLETION_TOUCHED_DURATION 20 MINUTES
#define SUCCUBUS_DEPLETION_DRAINED_DURATION 40 MINUTES
#define SUCCUBUS_DEPLETION_HOLLOWED_DURATION 60 MINUTES
#define SUCCUBUS_DEPLETION_TOUCHED_NUTRITION 75
#define SUCCUBUS_DEPLETION_DRAINED_NUTRITION 100
#define SUCCUBUS_DEPLETION_HOLLOWED_NUTRITION 125
/// Package B: evidence testing and Church relief.
#define SUCCUBUS_BLESSED_WATER_MAX_BURN 5
#define SUCCUBUS_DELIVERANCE_CHANNEL 8 SECONDS
#define SUCCUBUS_DELIVERANCE_COOLDOWN 2 MINUTES
#define SUCCUBUS_DELIVERANCE_DEVOTION_COST 60
/// Package C: bounded Church protection.
#define SUCCUBUS_CONSECRATION_CHANNEL 10 SECONDS
#define SUCCUBUS_CONSECRATION_COOLDOWN 5 MINUTES
#define SUCCUBUS_CONSECRATION_DEVOTION_COST 100
#define SUCCUBUS_CONSECRATION_DURATION 10 MINUTES
#define SUCCUBUS_CONSECRATION_INTEGRITY 100
#define SUCCUBUS_RIFT_SEAL_RITE_CHANNEL 8 SECONDS
#define SUCCUBUS_RIFT_SEAL_RITE_COOLDOWN 2 MINUTES
#define SUCCUBUS_RIFT_SEAL_RITE_DEVOTION_COST 100
#define SUCCUBUS_RIFT_SEAL_RITE_PROGRESS 2
#define SUCCUBUS_FATAL_DRAIN_UNLOCK_TIER 3
#define SUCCUBUS_FATAL_DRAIN_REWARD 200
#define SUCCUBUS_FATAL_DRAIN_CHANNEL 8 SECONDS
#define SUCCUBUS_FATAL_DRAIN_COOLDOWN 5 MINUTES
#define SUCCUBUS_FATAL_DRAIN_PROMPT_TIMEOUT 30 SECONDS
/// Max stored identity snapshots in the camouflage wardrobe
#define SUCCUBUS_WARDROBE_CAP 5
/// Created mortal identities unlock one fixed slot per contract tier.
#define SUCCUBUS_CREATED_DISGUISE_MAX_SLOTS SUCCUBUS_CONTRACT_TIER_MAX
#define SUCCUBUS_FORM_KEY_STARTING "succubus_starting_disguise"
#define SUCCUBUS_FORM_KEY_CREATED_PREFIX "succubus_created_disguise_"
/// One-way gateway destinations
#define SUCCUBUS_DEPLOYMENT_OUTSKIRTS "Outskirts"
#define SUCCUBUS_DEPLOYMENT_SEWERS "Sewers"
/// Essence costs
#define SUCCUBUS_COST_CAMOUFLAGE 15
#define SUCCUBUS_COST_CREATE_DISGUISE 50
#define SUCCUBUS_COST_LUST 25
#define SUCCUBUS_COST_APHRODISIAC_KISS 20
/// Multiplier on horny-KO thresholds for TRAIT_LUSTFUL_STAMINA holders —
/// tiring out a succubus in bed should be a heroic feat, not an afternoon
#define SUCCUBUS_HORNY_KO_MULT 10
/// Essence per unit of absorbed sexual fluid, before decay
#define SUCCUBUS_ESSENCE_PER_REAGENT_UNIT 1
/// Per-originator decay: multiplier compounds per SUCCUBUS_REAGENT_DECAY_UNIT units absorbed
#define SUCCUBUS_REAGENT_DECAY 0.5
#define SUCCUBUS_REAGENT_DECAY_UNIT 20
/// Camouflage integrity: forced reveal below this health fraction
#define SUCCUBUS_FORM_BREAK_HEALTH_FRACTION 0.4
/// Allure
#define SUCCUBUS_ALLURE_RANGE 3
/// True form
#define SUCCUBUS_TRUE_FORM_UNLOCK_TIER 2
#define SUCCUBUS_TRUE_FORM_PRESENCE_RANGE 3
#define SUCCUBUS_TRUE_FORM_PRESENCE_KNOCKDOWN 1.5 SECONDS
#define SUCCUBUS_TRUE_FORM_PRESENCE_IMMOBILIZE 0.75 SECONDS
#define SUCCUBUS_TRUE_FORM_CLAW_COOLDOWN 2 SECONDS
#define SUCCUBUS_TRUE_FORM_GAZE_RANGE 5
#define SUCCUBUS_TRUE_FORM_GAZE_CHARGE_TIME 2 SECONDS
#define SUCCUBUS_TRUE_FORM_GAZE_COOLDOWN 0.5 MINUTES
#define SUCCUBUS_TRUE_FORM_GAZE_IMMOBILIZE 5.5 SECONDS
#define SUCCUBUS_TRUE_FORM_GAZE_MESMERISED_DURATION 8 SECONDS
#define SUCCUBUS_TRUE_FORM_WINGBEAT_RANGE 5
#define SUCCUBUS_TRUE_FORM_WINGBEAT_COOLDOWN 25 SECONDS
#define SUCCUBUS_TRUE_FORM_TAIL_SWEEP_RANGE 1
#define SUCCUBUS_TRUE_FORM_TAIL_SWEEP_THROW_RANGE 2
#define SUCCUBUS_TRUE_FORM_TAIL_SWEEP_KNOCKDOWN 1 SECONDS
#define SUCCUBUS_TRUE_FORM_TAIL_SWEEP_COOLDOWN 20 SECONDS
/// Enthrall
#define SUCCUBUS_COST_ENTHRALL 150
#define SUCCUBUS_THRALL_CAP 3
#define SUCCUBUS_ENTHRALL_PROMPT_TIMEOUT 30 SECONDS
#define SUCCUBUS_THRALL_UPKEEP_PER_CYCLE 15
/// Harvests from a partner before their will can be bound
#define SUCCUBUS_ENTHRALL_MIN_HARVESTS 3
/// Whisper / Charm
#define SUCCUBUS_COST_WHISPER 5
#define SUCCUBUS_COST_CHARM 15
#define SUCCUBUS_CHARM_COOLDOWN 2 MINUTES
/// Beguiling Doubles
#define SUCCUBUS_BEGUILING_DOUBLES_UNLOCK_TIER 2
#define SUCCUBUS_COST_BEGUILING_DOUBLES 25
#define SUCCUBUS_BEGUILING_DOUBLES_COOLDOWN 1 MINUTES
#define SUCCUBUS_BEGUILING_DOUBLE_COUNT 3
#define SUCCUBUS_BEGUILING_DOUBLE_DURATION 5 SECONDS
#define SUCCUBUS_BEGUILING_DOUBLE_STEP_DELAY 0.5 SECONDS
#define SUCCUBUS_BEGUILING_DOUBLE_STEPS 6
/// Tier 3: Whispering Imp
#define SUCCUBUS_RETINUE_UNLOCK_TIER 3
#define SUCCUBUS_COST_SUMMON_IMP 75
#define SUCCUBUS_SUMMON_IMP_COOLDOWN 10 MINUTES
#define SUCCUBUS_SUMMON_IMP_RETRY_COOLDOWN 30 SECONDS
#define SUCCUBUS_SUMMON_IMP_POLL_TIME 15 SECONDS
#define SUCCUBUS_SUMMON_IMP_CAP 1
#define SUCCUBUS_SUMMON_IMP_DURATION 30 MINUTES
#define SUCCUBUS_SUMMON_IMP_WARNING_TIME 1 MINUTES
/// Tier 3: Infernal Snare
#define SUCCUBUS_COST_INFERNAL_SNARE 30
#define SUCCUBUS_INFERNAL_SNARE_COOLDOWN 45 SECONDS
#define SUCCUBUS_INFERNAL_SNARE_CAP 2
#define SUCCUBUS_INFERNAL_SNARE_DURATION 10 MINUTES
#define SUCCUBUS_INFERNAL_SNARE_IMMOBILIZE 3 SECONDS
#define SUCCUBUS_INFERNAL_SNARE_KNOCKDOWN 1 SECONDS
/// Tier 3: Lustbound Hound
#define SUCCUBUS_COST_SUMMON_LUSTHOUND 75
#define SUCCUBUS_SUMMON_LUSTHOUND_COOLDOWN 10 MINUTES
#define SUCCUBUS_SUMMON_LUSTHOUND_CAP 1
#define SUCCUBUS_SUMMON_LUSTHOUND_DURATION 10 MINUTES
/// Tier 4: Rift of Lust
#define SUCCUBUS_RIFT_UNLOCK_TIER 4
#define SUCCUBUS_RIFT_STAGE_COST 100
#define SUCCUBUS_RIFT_STAGE_SEED 1
#define SUCCUBUS_RIFT_STAGE_WIDENED 2
#define SUCCUBUS_RIFT_STAGE_OPEN 3
#define SUCCUBUS_RIFT_STAGE_ASCENDED 4
#define SUCCUBUS_RIFT_SEED_CHANNEL 20 SECONDS
#define SUCCUBUS_RIFT_WIDEN_CHANNEL 30 SECONDS
#define SUCCUBUS_RIFT_OPEN_CHANNEL 45 SECONDS
#define SUCCUBUS_RIFT_MATURATION 3 MINUTES
#define SUCCUBUS_RIFT_RETRY_COOLDOWN 10 MINUTES
#define SUCCUBUS_RIFT_DEFEAT_PROMPT_TIMEOUT 30 SECONDS
#define SUCCUBUS_RIFT_ACTION_COOLDOWN 5 SECONDS
#define SUCCUBUS_RIFT_SEED_INTEGRITY 100
#define SUCCUBUS_RIFT_WIDENED_INTEGRITY 200
#define SUCCUBUS_RIFT_OPEN_INTEGRITY 350
#define SUCCUBUS_RIFT_TRIAL_DURATION 5 MINUTES
#define SUCCUBUS_RIFT_WAVE_INTERVAL 45 SECONDS
#define SUCCUBUS_RIFT_WAVE_SIZE 4
#define SUCCUBUS_RIFT_MIN_ACTIVE_DEMONS 4
#define SUCCUBUS_RIFT_MAX_ACTIVE_DEMONS 12
#define SUCCUBUS_RIFT_PLAYERS_PER_DEMON 8
#define SUCCUBUS_RIFT_TOTAL_DEMON_MARGIN 8
#define SUCCUBUS_RIFT_HELLHOUND_CHANCE 30
#define SUCCUBUS_RIFT_SPAWN_RADIUS 3
#define SUCCUBUS_RIFT_SEAL_CHANNEL 10 SECONDS
#define SUCCUBUS_RIFT_SEAL_CONTRIBUTIONS 3
