#define VERIFIED_BYOND (1 << 0)
#define VERIFIED_DISCORD (1 << 1)
#define VERIFIED_ID (1 << 2)
#define VERIFIED_DEBUG (1 << 3) //! if someone has this shit fucked

DEFINE_BITFIELD(veyra_flags, list(
	"VERIFIED_BYOND" = VERIFIED_BYOND,
	"VERIFIED_DISCORD" = VERIFIED_DISCORD,
	"VERIFIED_ID" = VERIFIED_ID,
	"VERIFIED_DEBUG" = VERIFIED_DEBUG
))
