/*
			< ATTENTION >
	If you need to add more map_adjustment, check 'map_adjustment_include.dm'
	These 'map_adjustment.dm' files shouldn't be included in 'dme'
*/

/datum/map_adjustment/voyager
	map_file_name = "voyager.dmm"
	blacklist = list(
		/datum/job/advclass/burgmeister/marshall,
		/datum/job/advclass/burgmeister/elected,
		/datum/job/advclass/burgmeister/patrician,
		/datum/job/advclass/burgmeister/scholar,
		/datum/job/advclass/councilor/adjutant,
		/datum/job/advclass/councilor/clerk,
		/datum/job/advclass/councilor/advisor,
		/datum/job/advclass/councilor/spymaster,
		/datum/job/servant,
		/datum/job/watch_captain,
		/datum/job/watch_sergeant,
		/datum/job/watch_veteran,
		/datum/job/watch_warden,
		/datum/job/advclass/watch_guard/bulwark,
		/datum/job/advclass/watch_guard/halberdier,
		/datum/job/advclass/watch_guard/sentinel,
		/datum/job/acolyte,
		/datum/job/guild_wizard,
		/datum/job/guild_wizard_apprentice,
		/datum/job/advclass/town_scholar/explorer,
		/datum/job/advclass/town_scholar/archivist,
		/datum/job/advclass/town_scholar/artificer,
		/datum/job/advclass/town_scholar/town_physician,
		/datum/job/town_scholar_apprentice,
		/datum/job/waterdeep_banker,
		/datum/job/waterdeep_guild_guard,
		/datum/job/waterdeep_guild_assistant,
		/datum/job/adventurers_guildmaster,
		/datum/job/adventurers_assistant,
		/datum/job/matron,
		/datum/job/advclass/tavern_wench/bath_wench,
		/datum/job/seelie,
		/datum/job/advclass/towner/commoner,
		/datum/job/advclass/towner/burgess,
		/datum/job/advclass/towner/patrician,
		/datum/job/advclass/towner/town_mouth,
		/datum/job/advclass/towner/bard,
		/datum/job/advclass/towner/jester,
		/datum/job/advclass/towner/lumberjack,
		/datum/job/advclass/towner/farmhand,
		/datum/job/advclass/towner/hunter,
		/datum/job/artisan_apprentice,
		/datum/job/advclass/artisan/carpenter,
		/datum/job/advclass/artisan/mason,
		/datum/job/forest_warden,
		/datum/job/forest_ranger,
		/datum/job/grove_druid,
		/datum/job/swamp_witch,
		/datum/job/ogre,
		)
	slot_adjust = list(
		/datum/job/artisan = 4,
		/datum/job/advclass/artisan/blacksmith = 2,
		/datum/job/advclass/artisan/tailor = 2,
		/datum/job/town_scholar = 1,
		/datum/job/navigator = 2,
		/datum/job/watch_guard = 4,
		/datum/job/cook = 1,
		/datum/job/tavern_wench = 2,
		/datum/job/towner = 10,
		/datum/job/advclass/towner/miner = 2,
		/datum/job/advclass/towner/fisher = 3,
		/datum/job/advclass/towner/passenger = 5,)
