/// Tests for the TGUI character setup menu helpers.
/datum/unit_test/character_menu_scale_sanitize/Run()
	var/datum/preferences/prefs = allocate(/datum/preferences)
	TEST_ASSERT_EQUAL(prefs.character_setup_sanitize_preferences_scale("garbage"), 0.85, "Non-numeric scale should fall back to 0.85")
	TEST_ASSERT_EQUAL(prefs.character_setup_sanitize_preferences_scale(0.1), 0.8, "Scale should clamp up to 0.8")
	TEST_ASSERT_EQUAL(prefs.character_setup_sanitize_preferences_scale(5), 1.25, "Scale should clamp down to 1.25")
	TEST_ASSERT_EQUAL(prefs.character_setup_sanitize_preferences_scale(1.02), 1, "Scale should round to 0.05 steps")

/datum/unit_test/character_menu_clean_text/Run()
	var/datum/preferences/prefs = allocate(/datum/preferences)
	TEST_ASSERT_EQUAL(prefs.character_setup_chargen_clean_text("<b>bold</b> text"), "bold text", "HTML should be stripped")
	TEST_ASSERT_EQUAL(prefs.character_setup_chargen_clean_text("line\nbreak"), "line break", "Newlines should become spaces")
	TEST_ASSERT_EQUAL(prefs.character_setup_chargen_clean_text(null), "", "Null should return empty string")

/datum/unit_test/character_menu_art_bounds/Run()
	var/icon/blank = icon('icons/blanks/32x32.dmi', "nothing")
	TEST_ASSERT_NULL(character_setup_art_bounds(blank), "Fully transparent icon should have null art bounds")
	var/icon/dot = icon('icons/blanks/32x32.dmi', "nothing")
	dot.DrawBox("#ffffff", 5, 7)
	var/list/bounds = character_setup_art_bounds(dot)
	TEST_ASSERT_NOTNULL(bounds, "Icon with one pixel should have art bounds")
	TEST_ASSERT_EQUAL(bounds[1], 5, "x1 should be 5")
	TEST_ASSERT_EQUAL(bounds[2], 7, "y1 should be 7")
	TEST_ASSERT_EQUAL(bounds[3], 5, "x2 should be 5")
	TEST_ASSERT_EQUAL(bounds[4], 7, "y2 should be 7")

/datum/unit_test/character_menu_ooc_record/Run()
	GLOB.character_setup_chargen_ooc_messages.Cut()
	character_setup_chargen_record_ooc("Tester", "<script>hello</script> world")
	TEST_ASSERT_EQUAL(length(GLOB.character_setup_chargen_ooc_messages), 1, "One OOC message should be recorded")
	var/list/entry = GLOB.character_setup_chargen_ooc_messages[1]
	TEST_ASSERT_EQUAL(entry["sender"], "Tester", "Sender should be preserved")
	TEST_ASSERT(findtext(entry["message"], "world"), "Message body should survive")
	TEST_ASSERT(!findtext(entry["message"], "<"), "HTML should be stripped from OOC")
	character_setup_chargen_record_ooc(null, "no sender")
	TEST_ASSERT_EQUAL(length(GLOB.character_setup_chargen_ooc_messages), 1, "Non-text sender should be rejected")
	for(var/i in 1 to 45)
		character_setup_chargen_record_ooc("Spam", "msg [i]")
	TEST_ASSERT(length(GLOB.character_setup_chargen_ooc_messages) <= 40, "OOC buffer should cap at 40")
	GLOB.character_setup_chargen_ooc_messages.Cut()

/datum/unit_test/character_menu_loadout_data/Run()
	var/datum/preferences/prefs = allocate(/datum/preferences)
	var/list/slots = prefs.character_setup_loadout_slots_data()
	TEST_ASSERT_EQUAL(length(slots), 10, "Loadout slots data should cover 10 slots")
	var/list/first = slots[1]
	TEST_ASSERT_EQUAL(first["slot"], 1, "First slot entry should be slot 1")
	TEST_ASSERT_NULL(first["typepath"], "Fresh prefs should have an empty slot 1")

	var/list/points = prefs.character_setup_loadout_points_data()
	TEST_ASSERT_EQUAL(points["total"], prefs.get_base_points(), "Points total should match base points")
	TEST_ASSERT_EQUAL(points["remaining"], points["total"] - points["spent"], "Points math should be consistent")

	var/list/presets = prefs.character_setup_loadout_presets_data()
	TEST_ASSERT_EQUAL(length(presets), 3, "Presets data should cover 3 preset slots")

/datum/unit_test/character_menu_loadout_catalog/Run()
	var/datum/preferences/prefs = allocate(/datum/preferences)
	var/mob/living/carbon/human/dummy = allocate(/mob/living/carbon/human)
	var/list/catalog = prefs.character_setup_loadout_static(dummy)
	TEST_ASSERT(length(catalog), "Loadout catalog should not be empty (GLOB.loadout_items fills at world init)")
	var/list/entry = catalog[1]
	TEST_ASSERT(entry["name"], "Catalog entry needs a name")
	TEST_ASSERT(entry["typepath"], "Catalog entry needs a typepath")
	TEST_ASSERT(entry["icon"], "Catalog entry needs a spritesheet css class")

/datum/unit_test/character_menu_loadout_color/Run()
	var/datum/preferences/prefs = allocate(/datum/preferences)
	TEST_ASSERT(prefs.character_setup_apply_loadout_color(3, "Red"), "Applying a dye-list color should succeed")
	TEST_ASSERT_EQUAL(prefs.loadout_3_hex, GLOB.colorlist["Red"], "Named dye choice must store its hex value")
	TEST_ASSERT(prefs.character_setup_apply_loadout_color(3, "None"), "Choosing None should succeed")
	TEST_ASSERT_NULL(prefs.loadout_3_hex, "None should clear the stored hex")
	TEST_ASSERT(!prefs.character_setup_apply_loadout_color(3, "Custom"), "The Custom sentinel must never be stored directly")
	TEST_ASSERT(!prefs.character_setup_apply_loadout_color(99, "Red"), "Out-of-range slot should fail")
