/// Tests for the TGUI character setup menu helpers.
/datum/unit_test/character_menu_scale_sanitize/Run()
	var/datum/preferences/prefs = allocate(/datum/preferences)
	TEST_ASSERT_EQUAL(prefs.character_setup_sanitize_preferences_scale("garbage"), 0.85, "Non-numeric scale should fall back to 0.85")
	TEST_ASSERT_EQUAL(prefs.character_setup_sanitize_preferences_scale(0.1), 0.8, "Scale should clamp up to 0.8")
	TEST_ASSERT_EQUAL(prefs.character_setup_sanitize_preferences_scale(5), 1.25, "Scale should clamp down to 1.25")
	TEST_ASSERT_EQUAL(prefs.character_setup_sanitize_preferences_scale(1.02), 1, "Scale should round to 0.05 steps")

/datum/unit_test/character_menu_clean_text/Run()
	var/datum/preferences/prefs = allocate(/datum/preferences)
	TEST_ASSERT_EQUAL(prefs.character_setup_chargen_clean_text("<b>bold</b> text"), "bold text", "HTML should be stripped")
	TEST_ASSERT_EQUAL(prefs.character_setup_chargen_clean_text("line\nbreak"), "line break", "Newlines should become spaces")
	TEST_ASSERT_EQUAL(prefs.character_setup_chargen_clean_text(null), "", "Null should return empty string")

/datum/unit_test/character_menu_art_bounds/Run()
	var/icon/blank = icon('icons/blanks/32x32.dmi', "nothing")
	TEST_ASSERT_NULL(character_setup_art_bounds(blank), "Fully transparent icon should have null art bounds")
	var/icon/dot = icon('icons/blanks/32x32.dmi', "nothing")
	dot.DrawBox("#ffffff", 5, 7)
	var/list/bounds = character_setup_art_bounds(dot)
	TEST_ASSERT_NOTNULL(bounds, "Icon with one pixel should have art bounds")
	TEST_ASSERT_EQUAL(bounds[1], 5, "x1 should be 5")
	TEST_ASSERT_EQUAL(bounds[2], 7, "y1 should be 7")
	TEST_ASSERT_EQUAL(bounds[3], 5, "x2 should be 5")
	TEST_ASSERT_EQUAL(bounds[4], 7, "y2 should be 7")

/datum/unit_test/character_menu_ooc_record/Run()
	GLOB.character_setup_chargen_ooc_messages.Cut()
	character_setup_chargen_record_ooc("Tester", "<script>hello</script> world")
	TEST_ASSERT_EQUAL(length(GLOB.character_setup_chargen_ooc_messages), 1, "One OOC message should be recorded")
	var/list/entry = GLOB.character_setup_chargen_ooc_messages[1]
	TEST_ASSERT_EQUAL(entry["sender"], "Tester", "Sender should be preserved")
	TEST_ASSERT(findtext(entry["message"], "world"), "Message body should survive")
	TEST_ASSERT(!findtext(entry["message"], "<"), "HTML should be stripped from OOC")
	character_setup_chargen_record_ooc(null, "no sender")
	TEST_ASSERT_EQUAL(length(GLOB.character_setup_chargen_ooc_messages), 1, "Non-text sender should be rejected")
	for(var/i in 1 to 45)
		character_setup_chargen_record_ooc("Spam", "msg [i]")
	TEST_ASSERT(length(GLOB.character_setup_chargen_ooc_messages) <= 40, "OOC buffer should cap at 40")
	GLOB.character_setup_chargen_ooc_messages.Cut()
