/// Gives a test human the organs in [slots].
/datum/unit_test/proc/give_chastity_test_organs(mob/living/carbon/human/human, list/slots)
	var/static/list/organ_types = list(
		ORGAN_SLOT_PENIS = /obj/item/organ/genitals/penis,
		ORGAN_SLOT_TESTICLES = /obj/item/organ/genitals/filling_organ/testicles,
		ORGAN_SLOT_VAGINA = /obj/item/organ/genitals/filling_organ/vagina,
		ORGAN_SLOT_ANUS = /obj/item/organ/genitals/filling_organ/anus,
	)
	for(var/slot in slots)
		var/obj/item/organ/organ = allocate(organ_types[slot])
		organ.Insert(human, TRUE, FALSE)

/datum/unit_test/proc/fit_chastity_test_device(mob/living/carbon/human/human, device_type)
	var/obj/item/clothing/undies/chastity/device = allocate(device_type)
	human.equip_to_slot_if_possible(device, ITEM_SLOT_UNDER_BOTTOM, disable_warning = TRUE)
	return device

/datum/unit_test/chastity_devices_block_only_their_organs/Run()
	var/list/slots = list(ORGAN_SLOT_PENIS, ORGAN_SLOT_TESTICLES, ORGAN_SLOT_VAGINA, ORGAN_SLOT_ANUS)
	for(var/device_type in subtypesof(/obj/item/clothing/undies/chastity))
		var/mob/living/carbon/human/human = allocate(/mob/living/carbon/human)
		give_chastity_test_organs(human, slots)
		var/obj/item/clothing/undies/chastity/device = fit_chastity_test_device(human, device_type)
		TEST_ASSERT_EQUAL(human.underwear, device, "[device_type] should fit a body with every organ.")
		for(var/slot in slots)
			TEST_ASSERT_EQUAL(human.is_organ_slot_blocked(slot), !!(slot in device.blocked_organ_slots), "[device_type] blocked the wrong organs at [slot].")
		TEST_ASSERT(!human.is_organ_slot_blocked(ORGAN_SLOT_TESTICLES), "[device_type] should never block the testicles.")
		TEST_ASSERT(human.dropItemToGround(device), "An unlocked [device_type] should come off.")
		for(var/slot in slots)
			TEST_ASSERT(!human.is_organ_slot_blocked(slot), "Removing [device_type] should free [slot].")

/datum/unit_test/chastity_device_needs_matching_genitals/Run()
	var/mob/living/carbon/human/pussy_only = allocate(/mob/living/carbon/human)
	give_chastity_test_organs(pussy_only, list(ORGAN_SLOT_VAGINA))
	var/mob/living/carbon/human/cock_only = allocate(/mob/living/carbon/human)
	give_chastity_test_organs(cock_only, list(ORGAN_SLOT_PENIS))
	var/mob/living/carbon/human/bare = allocate(/mob/living/carbon/human)

	var/obj/item/clothing/undies/chastity/cage/cage = allocate(/obj/item/clothing/undies/chastity/cage)
	var/obj/item/clothing/undies/chastity/insertable/insertable = allocate(/obj/item/clothing/undies/chastity/insertable)
	var/obj/item/clothing/undies/chastity/intersex/intersex = allocate(/obj/item/clothing/undies/chastity/intersex)
	var/obj/item/clothing/undies/chastity/belt/belt = allocate(/obj/item/clothing/undies/chastity/belt)
	TEST_ASSERT(!cage.can_fit_on(pussy_only), "A cage needs a cock.")
	TEST_ASSERT(cage.can_fit_on(cock_only), "A cage should fit a cock.")
	TEST_ASSERT(!insertable.can_fit_on(cock_only), "An insertable belt needs a pussy.")
	TEST_ASSERT(insertable.can_fit_on(pussy_only), "An insertable belt should fit a pussy.")
	TEST_ASSERT(!intersex.can_fit_on(cock_only), "An intersex device needs both.")
	TEST_ASSERT(belt.can_fit_on(bare), "A plain belt should fit any body.")
	TEST_ASSERT(!cock_only.equip_to_slot_if_possible(insertable, ITEM_SLOT_UNDER_BOTTOM, disable_warning = TRUE), "Equipping should refuse a device that doesn't fit.")

/datum/unit_test/chastity_lock_keeps_device_on/Run()
	var/mob/living/carbon/human/human = allocate(/mob/living/carbon/human)
	var/mob/living/carbon/human/stripper = allocate(/mob/living/carbon/human)
	give_chastity_test_organs(human, list(ORGAN_SLOT_PENIS))
	var/obj/item/clothing/undies/chastity/cage/cage = fit_chastity_test_device(human, /obj/item/clothing/undies/chastity/cage)
	cage.lock.lock()
	TEST_ASSERT(cage.locked(), "The cage should lock.")
	TEST_ASSERT(!human.dropItemToGround(cage), "A locked cage should stay on.")
	TEST_ASSERT_EQUAL(human.underwear, cage, "A locked cage should still be worn.")
	TEST_ASSERT(!cage.canStrip(stripper, human), "A locked cage should not be strippable.")

	give_chastity_test_organs(stripper, list(ORGAN_SLOT_PENIS))
	var/obj/item/clothing/undies/chastity/cage/spare = allocate(/obj/item/clothing/undies/chastity/cage)
	TEST_ASSERT(spare.can_fit_on(stripper), "An open spare cage should fit a cock.")
	spare.lock.lock()
	TEST_ASSERT(!spare.can_fit_on(stripper), "A locked device should not fit anyone.")

	cage.lock.unlock()
	TEST_ASSERT(cage.canStrip(stripper, human), "An unlocked cage should be strippable.")
	TEST_ASSERT(human.dropItemToGround(cage), "An unlocked cage should come off.")

/datum/unit_test/chastity_key_access_and_hard_mode/Run()
	var/mob/living/carbon/human/human = allocate(/mob/living/carbon/human)
	give_chastity_test_organs(human, list(ORGAN_SLOT_PENIS))
	var/obj/item/clothing/undies/chastity/cage/cage = fit_chastity_test_device(human, /obj/item/clothing/undies/chastity/cage)
	var/datum/lock/key/chastity/cage_lock = cage.lock
	cage_lock.lock()
	var/obj/item/key/chastity/key = cage.get_generated_key()
	TEST_ASSERT_NOTNULL(key, "A device should come with its own key.")
	var/obj/item/key/copy = allocate(/obj/item/key)
	copy.lockids = key.lockids.Copy()
	var/obj/item/key/master = allocate(/obj/item/key)
	master.lockids = list(ACCESS_LORD)
	var/obj/item/storage/keyring/keyring = allocate(/obj/item/storage/keyring)
	key.forceMove(keyring)

	TEST_ASSERT(cage_lock.check_access(key), "The device's own key should fit.")
	TEST_ASSERT(cage_lock.check_access(copy), "A copied key should fit outside hard mode.")
	TEST_ASSERT(cage_lock.check_access(master), "A master key should fit outside hard mode.")
	TEST_ASSERT(cage.can_be_picked(), "A locked device should be pickable outside hard mode.")

	human.set_cached_erp_preferences(list(/datum/erp_preference/boolean/chastity_hardmode = TRUE))
	TEST_ASSERT(cage.is_hardmode_active(), "The wearer's hard mode pref should count.")
	TEST_ASSERT(cage_lock.check_access(key), "Hard mode should still accept the device's own key.")
	TEST_ASSERT(cage_lock.check_access(keyring), "Hard mode should accept a keyring holding the key.")
	TEST_ASSERT(!cage_lock.check_access(copy), "Hard mode should refuse a copied key.")
	TEST_ASSERT(!cage_lock.check_access(master), "Hard mode should refuse the master key.")
	TEST_ASSERT(!cage.can_be_picked(), "Hard mode should refuse lockpicks.")

/datum/unit_test/chastity_chisel_breaks_lock_without_harm/Run()
	var/mob/living/carbon/human/human = allocate(/mob/living/carbon/human)
	var/mob/living/carbon/human/smith = allocate(/mob/living/carbon/human)
	give_chastity_test_organs(human, list(ORGAN_SLOT_PENIS))
	var/obj/item/clothing/undies/chastity/cage/cage = fit_chastity_test_device(human, /obj/item/clothing/undies/chastity/cage)
	cage.lock.lock()
	var/obj/item/weapon/chisel/chisel = allocate(/obj/item/weapon/chisel)
	var/obj/item/weapon/hammer/hammer = allocate(/obj/item/weapon/hammer)
	smith.put_in_active_hand(chisel, forced = TRUE)
	smith.put_in_inactive_hand(hammer)
	TEST_ASSERT(cage.can_chisel(smith, chisel), "A chisel and hammer should be able to work the lock.")

	human.set_cached_erp_preferences(list(/datum/erp_preference/boolean/chastity_hardmode = TRUE))
	TEST_ASSERT(!cage.can_chisel(smith, chisel), "Hard mode should refuse the chisel.")
	human.set_cached_erp_preferences(list(/datum/erp_preference/boolean/chastity_hardmode = FALSE))

	var/brute_before = human.getBruteLoss()
	cage.break_lock(smith)
	TEST_ASSERT_NULL(human.underwear, "A broken lock should free the wearer.")
	TEST_ASSERT(isturf(cage.loc), "With both hands on the tools, the freed device should fall to the floor.")
	TEST_ASSERT_EQUAL(human.getBruteLoss(), brute_before, "Chiselling should never hurt the wearer.")
	var/datum/lock/key/chastity/cage_lock = cage.lock
	cage_lock.try_toggle(smith, cage.get_generated_key(), FALSE)
	TEST_ASSERT(!cage.locked(), "A broken lock should never close again.")

/datum/unit_test/chastity_release_frees_locked_wearer/Run()
	var/mob/living/carbon/human/human = allocate(/mob/living/carbon/human)
	var/obj/item/clothing/undies/chastity/belt/belt = fit_chastity_test_device(human, /obj/item/clothing/undies/chastity/belt)
	belt.lock.lock()
	TEST_ASSERT(human.release_chastity_device(), "Release should work on a locked device.")
	TEST_ASSERT_NULL(human.underwear, "Release should take the device off.")
	TEST_ASSERT(!belt.locked(), "A released device should be unlocked.")

/datum/unit_test/chastity_shield_blocks_anal_actions/Run()
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human)
	var/mob/living/carbon/human/target = allocate(/mob/living/carbon/human)
	give_chastity_test_organs(target, list(ORGAN_SLOT_PENIS, ORGAN_SLOT_ANUS))
	var/datum/sex_action/rimming/rim = allocate(/datum/sex_action/rimming)
	var/datum/sex_action/masturbate/anus/finger = allocate(/datum/sex_action/masturbate/anus)
	var/datum/sex_action/masturbate/penis/stroke = allocate(/datum/sex_action/masturbate/penis)

	var/obj/item/clothing/undies/chastity/cage/cage = fit_chastity_test_device(target, /obj/item/clothing/undies/chastity/cage)
	TEST_ASSERT_NULL(rim.get_blocked_organ_slot(user, target), "A plain cage should leave the rear free.")
	TEST_ASSERT_EQUAL(stroke.get_blocked_organ_slot(target, target), ORGAN_SLOT_PENIS, "A cage should block stroking.")
	target.dropItemToGround(cage)

	fit_chastity_test_device(target, /obj/item/clothing/undies/chastity/cage/shield)
	TEST_ASSERT_EQUAL(rim.get_blocked_organ_slot(user, target), ORGAN_SLOT_ANUS, "An anal shield should block rimming.")
	TEST_ASSERT_EQUAL(finger.get_blocked_organ_slot(target, target), ORGAN_SLOT_ANUS, "An anal shield should block fingering yourself.")

/datum/unit_test/chastity_hides_covered_organ_sprites/Run()
	var/mob/living/carbon/human/human = allocate(/mob/living/carbon/human)
	give_chastity_test_organs(human, list(ORGAN_SLOT_PENIS, ORGAN_SLOT_TESTICLES))
	var/obj/item/organ/genitals/penis/penis = human.getorganslot(ORGAN_SLOT_PENIS)
	var/obj/item/organ/genitals/testicles = human.getorganslot(ORGAN_SLOT_TESTICLES)
	penis.accessory_type = /datum/sprite_accessory/genitals/penis/human
	penis.visible_through_clothes = DRAW_ABOVE
	var/datum/sprite_accessory/penis_accessory = SPRITE_ACCESSORY(/datum/sprite_accessory/genitals/penis/human)
	var/datum/sprite_accessory/ball_accessory = SPRITE_ACCESSORY(/datum/sprite_accessory/genitals/testicles/pair)
	var/bare_key = human.generate_icon_render_key()
	TEST_ASSERT(penis_accessory.is_visible(penis, null, human), "A bare cock set to show should be visible.")

	var/obj/item/clothing/undies/chastity/cage/cage = fit_chastity_test_device(human, /obj/item/clothing/undies/chastity/cage)
	TEST_ASSERT(!penis_accessory.is_visible(penis, null, human), "A cage should hide the cock even when it draws over clothes.")
	TEST_ASSERT(ball_accessory.is_visible(testicles, null, human), "A cage should leave the balls visible.")
	TEST_ASSERT_NOTEQUAL(human.generate_icon_render_key(), bare_key, "A caged cock should change the render key.")
	human.dropItemToGround(cage)

	testicles.visible_through_clothes = DRAW_ABOVE
	fit_chastity_test_device(human, /obj/item/clothing/undies/chastity/belt)
	TEST_ASSERT(!ball_accessory.is_visible(testicles, null, human), "A belt should hide the balls even when they draw over clothes.")

/datum/unit_test/chastity_leech_refuses_covered_organ/Run()
	var/mob/living/carbon/human/human = allocate(/mob/living/carbon/human)
	give_chastity_test_organs(human, list(ORGAN_SLOT_PENIS))
	var/obj/item/organ/penis = human.getorganslot(ORGAN_SLOT_PENIS)
	var/obj/item/natural/worms/leech/erotic/leech = allocate(/obj/item/natural/worms/leech/erotic)
	TEST_ASSERT(leech.can_attach_to_organ(human, penis), "A leech should latch onto a bare cock.")
	fit_chastity_test_device(human, /obj/item/clothing/undies/chastity/cage)
	TEST_ASSERT(!leech.can_attach_to_organ(human, penis), "A leech should not latch onto a caged cock.")

/datum/unit_test/chastity_quirk_locks_the_chosen_device/Run()
	var/mob/living/carbon/human/human = allocate(/mob/living/carbon/human)
	give_chastity_test_organs(human, list(ORGAN_SLOT_PENIS))
	TEST_ASSERT(human.add_quirk(/datum/quirk/peculiarity/kept_in_chastity, "[/obj/item/clothing/undies/chastity/cage]"), "The quirk should apply.")
	var/datum/quirk/peculiarity/kept_in_chastity/quirk = locate() in human.quirks
	quirk.after_job_spawn(null)
	TEST_ASSERT(istype(human.underwear, /obj/item/clothing/undies/chastity/cage), "The quirk should fit the chosen cage.")
	TEST_ASSERT(human.underwear.locked(), "The quirk's device should start locked.")
	var/obj/item/key/chastity/key = locate() in human.held_items
	TEST_ASSERT_NOTNULL(key, "The key should be on the wearer.")

	var/mob/living/carbon/human/lost = allocate(/mob/living/carbon/human)
	give_chastity_test_organs(lost, list(ORGAN_SLOT_PENIS))
	lost.add_quirk(/datum/quirk/peculiarity/kept_in_chastity, "[/obj/item/clothing/undies/chastity/cage]", list("key" = "Lost"))
	var/datum/quirk/peculiarity/kept_in_chastity/lost_quirk = locate() in lost.quirks
	lost_quirk.after_job_spawn(null)
	TEST_ASSERT(lost.underwear?.locked(), "A lost-key wearer should still be locked in.")
	TEST_ASSERT_NULL((locate(/obj/item/key/chastity) in lost.held_items), "A lost key should not be carried.")

	var/mob/living/carbon/human/mismatch = allocate(/mob/living/carbon/human)
	give_chastity_test_organs(mismatch, list(ORGAN_SLOT_PENIS))
	mismatch.add_quirk(/datum/quirk/peculiarity/kept_in_chastity, "[/obj/item/clothing/undies/chastity/insertable]")
	var/datum/quirk/peculiarity/kept_in_chastity/mismatch_quirk = locate() in mismatch.quirks
	mismatch_quirk.after_job_spawn(null)
	TEST_ASSERT_NULL(mismatch.underwear, "A device that doesn't fit should not be worn.")
	TEST_ASSERT_NOTNULL((locate(/obj/item/clothing/undies/chastity/insertable) in mismatch.held_items), "A device that doesn't fit should be carried.")

/datum/unit_test/chastity_sprites_exist/Run()
	var/list/item_states = icon_states('modular_rmh/icons/obj/lewd/chastity.dmi')
	var/list/worn_states = icon_states('modular_rmh/icons/obj/lewd/chastity_onmob.dmi')
	for(var/obj/item/clothing/undies/chastity/device_type as anything in subtypesof(/obj/item/clothing/undies/chastity))
		var/state = initial(device_type.icon_state)
		TEST_ASSERT(state in item_states, "[device_type] is missing item state [state].")
		var/list/device_worn_states = list(state)
		if(ispath(device_type, /obj/item/clothing/undies/chastity/arcane))
			var/obj/item/clothing/undies/chastity/arcane/arcane = allocate(device_type)
			device_worn_states = arcane.get_all_worn_states()
		for(var/worn_state in device_worn_states)
			for(var/suffix in list("", "_f", "_dwarf", "_f_dwarf"))
				TEST_ASSERT("[worn_state][suffix]" in worn_states, "[device_type] is missing worn state [worn_state][suffix].")

/datum/unit_test/arcane_chastity_modes_set_what_it_blocks/Run()
	var/mob/living/carbon/human/human = allocate(/mob/living/carbon/human)
	give_chastity_test_organs(human, list(ORGAN_SLOT_PENIS, ORGAN_SLOT_VAGINA, ORGAN_SLOT_ANUS))
	var/obj/item/clothing/undies/chastity/arcane/device = fit_chastity_test_device(human, /obj/item/clothing/undies/chastity/arcane)
	TEST_ASSERT_EQUAL(human.underwear, device, "The arcane device should fit.")
	TEST_ASSERT(human.is_organ_slot_blocked(ORGAN_SLOT_PENIS), "A sealed front should block the cock.")
	TEST_ASSERT(human.is_organ_slot_blocked(ORGAN_SLOT_VAGINA), "A sealed front should block the pussy.")
	TEST_ASSERT(human.is_organ_slot_blocked(ORGAN_SLOT_ANUS), "A sealed rear should block the anus.")

	TEST_ASSERT(device.set_front_mode(CHASTITY_FRONT_PENIS), "An intersex wearer should allow opening the cock.")
	TEST_ASSERT(!human.is_organ_slot_blocked(ORGAN_SLOT_PENIS), "An open cock should be usable.")
	TEST_ASSERT(human.is_organ_slot_blocked(ORGAN_SLOT_VAGINA), "Opening the cock should keep the pussy sealed.")
	TEST_ASSERT(device.set_front_mode(CHASTITY_FRONT_ALL), "An intersex wearer should allow opening everything.")
	TEST_ASSERT(!human.is_organ_slot_blocked(ORGAN_SLOT_VAGINA), "An open front should free the pussy.")
	TEST_ASSERT(!device.set_front_mode(CHASTITY_FRONT_ALL), "Setting the same mode twice should change nothing.")
	TEST_ASSERT(device.set_rear_open(TRUE), "The rear should open.")
	TEST_ASSERT(!human.is_organ_slot_blocked(ORGAN_SLOT_ANUS), "An open rear should free the anus.")

	var/mob/living/carbon/human/cock_only = allocate(/mob/living/carbon/human)
	give_chastity_test_organs(cock_only, list(ORGAN_SLOT_PENIS))
	var/obj/item/clothing/undies/chastity/arcane/cock_device = fit_chastity_test_device(cock_only, /obj/item/clothing/undies/chastity/arcane)
	TEST_ASSERT(!(CHASTITY_FRONT_VAGINA in cock_device.get_valid_front_modes()), "A body without a pussy should not offer opening one.")
	TEST_ASSERT(!cock_device.set_front_mode(CHASTITY_FRONT_ALL), "A body with one opening should refuse the all-open mode.")

/datum/unit_test/arcane_chastity_worn_look_follows_modes/Run()
	var/mob/living/carbon/human/cock_only = allocate(/mob/living/carbon/human)
	give_chastity_test_organs(cock_only, list(ORGAN_SLOT_PENIS, ORGAN_SLOT_TESTICLES))
	var/obj/item/clothing/undies/chastity/arcane/device = fit_chastity_test_device(cock_only, /obj/item/clothing/undies/chastity/arcane)
	TEST_ASSERT_EQUAL(device.get_worn_state(), "arcane_cage_shield", "A sealed cock should wear the arcane cage and shield.")
	var/mutable_appearance/worn = device.build_worn_icon(default_layer = UNDERWEAR_BOT_LAYER, coom = TRUE, customi = "dwarf")
	TEST_ASSERT_EQUAL(worn.icon_state, "arcane_cage_shield_f_dwarf", "The worn sprite should follow the device's mode and body.")
	TEST_ASSERT(device.hides_organ_slot(ORGAN_SLOT_PENIS), "The arcane cage should hide the cock.")
	TEST_ASSERT(!device.hides_organ_slot(ORGAN_SLOT_TESTICLES), "The arcane cage should show the balls.")
	TEST_ASSERT(device.set_flat(TRUE), "A cock wearer should allow flattening.")
	TEST_ASSERT_EQUAL(device.get_worn_state(), "arcane_flat_shield", "Flattening should switch to the flat look.")
	device.set_rear_open(TRUE)
	TEST_ASSERT_EQUAL(device.get_worn_state(), "arcane_flat", "An open rear should drop the shield.")
	device.set_front_mode(CHASTITY_FRONT_PENIS)
	TEST_ASSERT_EQUAL(device.get_worn_state(), "arcane_open", "An open front should leave only the strap.")
	TEST_ASSERT(!device.hides_organ_slot(ORGAN_SLOT_PENIS), "An open front should show the cock.")

	var/mob/living/carbon/human/intersex = allocate(/mob/living/carbon/human)
	give_chastity_test_organs(intersex, list(ORGAN_SLOT_PENIS, ORGAN_SLOT_VAGINA))
	var/obj/item/clothing/undies/chastity/arcane/intersex_device = fit_chastity_test_device(intersex, /obj/item/clothing/undies/chastity/arcane)
	TEST_ASSERT_EQUAL(intersex_device.get_worn_state(), "arcane_intersex_shield", "A sealed intersex body should wear the intersex look.")
	var/mob/living/carbon/human/bare = allocate(/mob/living/carbon/human)
	var/obj/item/clothing/undies/chastity/arcane/bare_device = fit_chastity_test_device(bare, /obj/item/clothing/undies/chastity/arcane)
	TEST_ASSERT_EQUAL(bare_device.get_worn_state(), "arcane_belt_shield", "A body without genitals should wear the belt look.")

/datum/unit_test/arcane_chastity_ignores_keys_and_tools/Run()
	var/mob/living/carbon/human/human = allocate(/mob/living/carbon/human)
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human)
	give_chastity_test_organs(human, list(ORGAN_SLOT_PENIS))
	var/obj/item/clothing/undies/chastity/arcane/device = fit_chastity_test_device(human, /obj/item/clothing/undies/chastity/arcane)
	TEST_ASSERT(device.set_arcane_locked(TRUE), "The arcane device should lock.")
	TEST_ASSERT(!human.dropItemToGround(device), "A locked arcane device should stay on.")
	TEST_ASSERT(!device.can_be_picked(), "An arcane device should never be pickable.")
	var/obj/item/key/master = allocate(/obj/item/key)
	master.lockids = list(ACCESS_LORD)
	user.zone_selected = BODY_ZONE_PRECISE_GROIN
	TEST_ASSERT_EQUAL(device.on_wearer_item_interaction(human, user, master, list()), ITEM_INTERACT_BLOCKING, "A key should bounce off the arcane device.")
	var/obj/item/weapon/chisel/chisel = allocate(/obj/item/weapon/chisel)
	TEST_ASSERT_EQUAL(device.on_wearer_item_interaction(human, user, chisel, list()), ITEM_INTERACT_BLOCKING, "A chisel should bounce off the arcane device.")
	TEST_ASSERT(device.locked(), "Keys and tools should not open the arcane device.")
	TEST_ASSERT(human.release_chastity_device(), "Turning chastity play off should still free the wearer.")
	TEST_ASSERT(!device.locked(), "A released arcane device should be unlocked.")

/datum/unit_test/arcane_chastity_binds_to_one_ring/Run()
	var/mob/living/carbon/human/human = allocate(/mob/living/carbon/human)
	var/mob/living/carbon/human/owner = allocate(/mob/living/carbon/human)
	var/obj/item/clothing/undies/chastity/arcane/device = fit_chastity_test_device(human, /obj/item/clothing/undies/chastity/arcane)
	var/obj/item/clothing/ring/slave_control/first = allocate(/obj/item/clothing/ring/slave_control)
	var/obj/item/clothing/ring/slave_control/second = allocate(/obj/item/clothing/ring/slave_control)
	var/obj/item/clothing/ring/slave_control/master/master = allocate(/obj/item/clothing/ring/slave_control/master)
	TEST_ASSERT(device.bind_ring(first, owner), "The device should bind to a ring.")
	TEST_ASSERT_EQUAL(first.bound_chastity, device, "The ring should know its device.")
	TEST_ASSERT_EQUAL(first.get_bound_chastity_wearer(), human, "The ring should find the wearer.")
	TEST_ASSERT(!device.bind_ring(second, owner), "A plain ring should not steal a bound device.")
	TEST_ASSERT(device.bind_ring(master, owner), "A master ring should take over a bound device.")
	TEST_ASSERT_NULL(first.bound_chastity, "The old ring should lose the device.")
	TEST_ASSERT_EQUAL(device.bound_ring, master, "The device should answer to the master ring.")
	qdel(master)
	TEST_ASSERT_NULL(device.bound_ring, "A destroyed ring should free the device.")

/datum/unit_test/arcane_chastity_ring_commands/Run()
	var/mob/living/carbon/human/human = allocate(/mob/living/carbon/human)
	var/mob/living/carbon/human/owner = allocate(/mob/living/carbon/human)
	give_chastity_test_organs(human, list(ORGAN_SLOT_PENIS))
	var/obj/item/clothing/undies/chastity/arcane/device = fit_chastity_test_device(human, /obj/item/clothing/undies/chastity/arcane)
	var/list/options = device.get_ring_command_options()
	TEST_ASSERT_EQUAL(options["Lock"], "lock", "An open device should offer locking.")
	TEST_ASSERT_EQUAL(options["Open cock"], "front_[CHASTITY_FRONT_PENIS]", "A cock wearer should be offered opening it.")
	TEST_ASSERT(!("Open pussy" in options), "A body without a pussy should not be offered opening one.")
	TEST_ASSERT(device.perform_ring_command("lock", owner), "The lock command should work.")
	TEST_ASSERT(device.locked(), "The lock command should lock the device.")
	TEST_ASSERT(!device.perform_ring_command("unlock", owner), "A second command inside the cooldown should fail.")
	TEST_ASSERT(device.locked(), "A refused command should change nothing.")

/datum/unit_test/chastity_moods_follow_faith_and_fit/Run()
	var/mob/living/carbon/human/human = allocate(/mob/living/carbon/human)
	give_chastity_test_organs(human, list(ORGAN_SLOT_PENIS))
	var/obj/item/organ/genitals/penis/penis = human.getorganslot(ORGAN_SLOT_PENIS)
	penis.organ_size = DEFAULT_PENIS_SIZE
	human.set_patron(/datum/patron/faerun/good_gods/Ilmater)
	human.add_quirk(/datum/quirk/vice/addiction/godfearing)
	var/obj/item/clothing/undies/chastity/cage/cage = fit_chastity_test_device(human, /obj/item/clothing/undies/chastity/cage)
	TEST_ASSERT_NOTNULL(human.has_stress_type(/datum/stress_event/chastity_devout), "A godfearing follower of Ilmater should find the cage steadying.")
	TEST_ASSERT_NULL(human.has_stress_type(/datum/stress_event/chastity_frustration), "Ilmater's follower should not chafe.")
	TEST_ASSERT_NULL(human.has_stress_type(/datum/stress_event/chastity_cramped), "A standard cage should not cramp.")
	human.dropItemToGround(cage)
	TEST_ASSERT_NULL(human.has_stress_type(/datum/stress_event/chastity_devout), "Taking the device off should clear its moods.")

	human.set_patron(/datum/patron/faerun/good_gods/Sune)
	fit_chastity_test_device(human, /obj/item/clothing/undies/chastity/cage/flat)
	TEST_ASSERT_NULL(human.has_stress_type(/datum/stress_event/chastity_devout), "Sune does not bless chastity.")
	TEST_ASSERT_NOTNULL(human.has_stress_type(/datum/stress_event/chastity_frustration), "Sune's follower should chafe in chastity.")
	TEST_ASSERT_NOTNULL(human.has_stress_type(/datum/stress_event/chastity_cramped), "A flat cage should cramp a full-sized cock.")

/datum/unit_test/chastity_caged_climax_dribbles_out/Run()
	var/mob/living/carbon/human/human = allocate(/mob/living/carbon/human)
	human.set_species(/datum/species/human/northern)
	give_chastity_test_organs(human, list(ORGAN_SLOT_PENIS, ORGAN_SLOT_TESTICLES))
	var/obj/item/organ/testes = human.getorganslot(ORGAN_SLOT_TESTICLES)
	testes.reagents.clear_reagents()
	testes.reagents.add_reagent(/datum/reagent/consumable/cum, 20)
	TEST_ASSERT_EQUAL(apply_sex_action_climax_effects(human, null, null, ORGASM_LOCATION_SELF, testes.reagents, 5, get_turf(human)), 5, "Nothing should catch a bare climax.")

	fit_chastity_test_device(human, /obj/item/clothing/undies/chastity/cage)
	TEST_ASSERT_EQUAL(apply_sex_action_climax_effects(human, null, null, ORGASM_LOCATION_SELF, testes.reagents, 5, get_turf(human)), 0, "A cage should catch its wearer's climax.")
	TEST_ASSERT(abs(testes.reagents.total_volume - 15) < 0.01, "The caught seed should leave the testicles.")

	var/mob/living/carbon/human/open = allocate(/mob/living/carbon/human)
	open.set_species(/datum/species/human/northern)
	give_chastity_test_organs(open, list(ORGAN_SLOT_PENIS, ORGAN_SLOT_TESTICLES))
	var/obj/item/organ/open_testes = open.getorganslot(ORGAN_SLOT_TESTICLES)
	open_testes.reagents.add_reagent(/datum/reagent/consumable/cum, 20)
	var/obj/item/clothing/undies/chastity/arcane/device = fit_chastity_test_device(open, /obj/item/clothing/undies/chastity/arcane)
	device.set_front_mode(CHASTITY_FRONT_PENIS)
	TEST_ASSERT_EQUAL(apply_sex_action_climax_effects(open, null, null, ORGASM_LOCATION_SELF, open_testes.reagents, 5, get_turf(open)), 5, "An opened cock should climax freely.")

/datum/unit_test/arcane_chastity_counts_partner_climaxes/Run()
	var/mob/living/carbon/human/wearer = allocate(/mob/living/carbon/human)
	var/mob/living/carbon/human/partner = allocate(/mob/living/carbon/human)
	wearer.set_species(/datum/species/human/northern)
	give_chastity_test_organs(partner, list(ORGAN_SLOT_PENIS, ORGAN_SLOT_TESTICLES))
	var/obj/item/organ/testes = partner.getorganslot(ORGAN_SLOT_TESTICLES)
	testes.reagents.add_reagent(/datum/reagent/consumable/cum, 20)
	var/obj/item/clothing/undies/chastity/arcane/device = fit_chastity_test_device(wearer, /obj/item/clothing/undies/chastity/arcane)
	apply_sex_action_climax_effects(partner, wearer, null, ORGASM_LOCATION_ONTO, testes.reagents, 5, wearer)
	TEST_ASSERT_EQUAL(device.tally_marks, 1, "A partner's climax on the wearer should add a tally mark.")
	apply_sex_action_climax_effects(partner, wearer, null, ORGASM_LOCATION_ONTO, testes.reagents, 5, wearer)
	TEST_ASSERT_EQUAL(device.tally_marks, 1, "Spurts of one climax should count once.")

/datum/unit_test/chastity_arousal_flavor_picks_the_right_bank/Run()
	var/mob/living/carbon/human/cock_only = allocate(/mob/living/carbon/human)
	give_chastity_test_organs(cock_only, list(ORGAN_SLOT_PENIS))
	var/obj/item/organ/genitals/penis/penis = cock_only.getorganslot(ORGAN_SLOT_PENIS)
	penis.organ_size = DEFAULT_PENIS_SIZE
	var/obj/item/clothing/undies/chastity/cage/cage = fit_chastity_test_device(cock_only, /obj/item/clothing/undies/chastity/cage)
	TEST_ASSERT_EQUAL(cage.get_arousal_flavor_key(list("arousal" = 0, "orgasm_progress" = 0)), "denial", "A calm caged cock should feel denied.")
	TEST_ASSERT_EQUAL(cage.get_arousal_flavor_key(list("arousal" = 45, "orgasm_progress" = 0)), "frustration", "Rising arousal should frustrate.")
	TEST_ASSERT_EQUAL(cage.get_arousal_flavor_key(list("arousal" = 70, "orgasm_progress" = 0)), "teasing", "High arousal should tease.")
	TEST_ASSERT_EQUAL(cage.get_arousal_flavor_key(list("arousal" = 70, "orgasm_progress" = 80)), "edge", "Near climax should be the edge.")
	penis.organ_size = MAX_PENIS_SIZE
	TEST_ASSERT_EQUAL(cage.get_arousal_flavor_key(list("arousal" = 0, "orgasm_progress" = 0)), "large_cock", "A big cock should get the cramped lines.")

	var/mob/living/carbon/human/pussy_only = allocate(/mob/living/carbon/human)
	give_chastity_test_organs(pussy_only, list(ORGAN_SLOT_VAGINA))
	var/obj/item/clothing/undies/chastity/insertable/belt = fit_chastity_test_device(pussy_only, /obj/item/clothing/undies/chastity/insertable)
	TEST_ASSERT_EQUAL(belt.get_arousal_flavor_key(list("arousal" = 0)), "vagina", "A sealed pussy should get the belt lines.")
	var/obj/item/organ/pussy = pussy_only.getorganslot(ORGAN_SLOT_VAGINA)
	pussy.reagents.add_reagent(/datum/reagent/consumable/cum, 5)
	TEST_ASSERT_EQUAL(belt.get_arousal_flavor_key(list("arousal" = 0)), "retention", "Seed sealed inside should get the retention lines.")

	var/mob/living/carbon/human/devout = allocate(/mob/living/carbon/human)
	give_chastity_test_organs(devout, list(ORGAN_SLOT_PENIS))
	devout.set_patron(/datum/patron/faerun/good_gods/Ilmater)
	devout.add_quirk(/datum/quirk/vice/addiction/godfearing)
	var/obj/item/clothing/undies/chastity/cage/devout_cage = fit_chastity_test_device(devout, /obj/item/clothing/undies/chastity/cage)
	TEST_ASSERT_EQUAL(devout_cage.get_arousal_flavor_key(list("arousal" = 0)), "devout", "A devout wearer should feel it as devotion.")

	var/mob/living/carbon/human/opened = allocate(/mob/living/carbon/human)
	give_chastity_test_organs(opened, list(ORGAN_SLOT_PENIS))
	var/obj/item/clothing/undies/chastity/arcane/device = fit_chastity_test_device(opened, /obj/item/clothing/undies/chastity/arcane)
	device.set_front_mode(CHASTITY_FRONT_PENIS)
	TEST_ASSERT_NULL(device.get_arousal_flavor_key(list("arousal" = 70)), "An opened front should give no chastity lines.")

/datum/unit_test/chastity_jingle_follows_wearer_and_cover/Run()
	var/mob/living/carbon/human/human = allocate(/mob/living/carbon/human)
	give_chastity_test_organs(human, list(ORGAN_SLOT_PENIS))
	var/obj/item/clothing/undies/chastity/cage/cage = fit_chastity_test_device(human, /obj/item/clothing/undies/chastity/cage)
	TEST_ASSERT_EQUAL(cage.get_jingle_key(cage.get_groin_cover_tier()), "jingle_bare", "A bare cage should jingle openly.")
	var/obj/item/clothing/pants/trou/trousers = allocate(/obj/item/clothing/pants/trou)
	human.equip_to_slot_if_possible(trousers, ITEM_SLOT_PANTS, disable_warning = TRUE)
	TEST_ASSERT_NOTEQUAL(cage.get_jingle_key(cage.get_groin_cover_tier()), "jingle_bare", "Trousers should muffle the jingle.")

	human.forceMove(get_step(human, EAST))
	TEST_ASSERT_EQUAL(cage.jingle_steps, 1, "Walking should count toward a jingle.")
	human.dropItemToGround(cage)
	human.forceMove(get_step(human, WEST))
	TEST_ASSERT_EQUAL(cage.jingle_steps, 0, "A removed cage should stop counting steps.")

/datum/unit_test/chastity_flavor_banks_have_every_key/Run()
	var/list/banks = list(
		"chastity_arousal_messages.json" = list("denial", "frustration", "teasing", "edge", "vagina", "retention", "devout", "intersex", "large_cock"),
		"chastity_movement_messages.json" = list("jingle_bare", "jingle_cloth", "jingle_light", "jingle_medium", "jingle_heavy", "struggle"),
		"chastity_receive_flavor.json" = list("devout", "cock_anal", "cock_general", "vagina_anal", "vagina_general", "intersex_anal", "intersex_general", "cock_self", "vagina_self", "intersex_self", "self_devout", "cock_touched", "vagina_touched", "intersex_touched", "touched_devout"),
		"chastity_lock_messages.json" = list("lock_click", "unlock_click", "hardmode_denial", "arcane_denial", "remote_lock", "remote_unlock"),
		"chastity_mode_messages.json" = list("front_close", "front_open", "rear_close", "rear_open", "flat_enable", "flat_disable", "bind"),
	)
	for(var/bank in banks)
		TEST_ASSERT(fexists("[CHASTITY_STRINGS_DIR]/[bank]"), "Missing message bank [bank].")
		for(var/key in banks[bank])
			TEST_ASSERT(check_strings(bank, key, CHASTITY_STRINGS_DIR), "[bank] is missing [key].")

/datum/unit_test/chastity_actions_need_the_right_device/Run()
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human)
	var/mob/living/carbon/human/wearer = allocate(/mob/living/carbon/human)
	give_chastity_test_organs(user, list(ORGAN_SLOT_PENIS, ORGAN_SLOT_VAGINA))
	give_chastity_test_organs(wearer, list(ORGAN_SLOT_PENIS, ORGAN_SLOT_VAGINA, ORGAN_SLOT_ANUS))
	var/datum/sex_action/chastity/hands/stroke_cock/stroke = allocate(/datum/sex_action/chastity/hands/stroke_cock)
	var/datum/sex_action/chastity/hands/rub_pussy/rub = allocate(/datum/sex_action/chastity/hands/rub_pussy)
	var/datum/sex_action/chastity/hands/tease_rear/tease = allocate(/datum/sex_action/chastity/hands/tease_rear)
	var/datum/sex_action/chastity/hands/fondle/fondle = allocate(/datum/sex_action/chastity/hands/fondle)
	var/datum/sex_action/chastity/hands/self_cock/self_stroke = allocate(/datum/sex_action/chastity/hands/self_cock)
	var/datum/sex_action/chastity/lick_belt/lick = allocate(/datum/sex_action/chastity/lick_belt)
	var/datum/sex_action/chastity/ride_cage/ride = allocate(/datum/sex_action/chastity/ride_cage)
	var/datum/sex_action/chastity/scissor_belt/scissor = allocate(/datum/sex_action/chastity/scissor_belt)
	TEST_ASSERT(!stroke.shows_on_menu(user, wearer), "No device should offer no chastity play.")

	var/obj/item/clothing/undies/chastity/cage/cage = fit_chastity_test_device(wearer, /obj/item/clothing/undies/chastity/cage)
	TEST_ASSERT(stroke.shows_on_menu(user, wearer), "A cage should offer stroking it.")
	TEST_ASSERT(stroke.can_perform(user, wearer), "A bare caged cock should be strokable.")
	TEST_ASSERT(fondle.shows_on_menu(user, wearer), "Any device should offer fondling.")
	TEST_ASSERT(ride.shows_on_menu(user, wearer), "A cage should offer riding it.")
	TEST_ASSERT(!rub.shows_on_menu(user, wearer), "A cage leaves the pussy bare.")
	TEST_ASSERT(!tease.shows_on_menu(user, wearer), "A plain cage has no rear shield.")
	TEST_ASSERT(!lick.shows_on_menu(user, wearer), "A cage has no belt to lick through.")
	TEST_ASSERT(!scissor.shows_on_menu(user, wearer), "A cage has no belt to scissor against.")
	TEST_ASSERT(self_stroke.shows_on_menu(wearer, wearer), "The wearer should be offered stroking their own cage.")
	TEST_ASSERT(!self_stroke.shows_on_menu(user, wearer), "A self action should not target a partner.")
	TEST_ASSERT(!stroke.shows_on_menu(wearer, wearer), "A partner action should not target oneself.")
	wearer.dropItemToGround(cage)

	fit_chastity_test_device(wearer, /obj/item/clothing/undies/chastity/intersex)
	TEST_ASSERT(rub.shows_on_menu(user, wearer), "An intersex device should offer rubbing the sealed pussy.")
	TEST_ASSERT(tease.shows_on_menu(user, wearer), "An intersex device should offer teasing the rear.")
	TEST_ASSERT(lick.shows_on_menu(user, wearer), "An intersex device should offer licking through it.")
	TEST_ASSERT(scissor.shows_on_menu(user, wearer), "An intersex device should offer scissoring.")

/datum/unit_test/chastity_actions_respect_the_pref/Run()
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human)
	var/mob/living/carbon/human/wearer = allocate(/mob/living/carbon/human)
	give_chastity_test_organs(wearer, list(ORGAN_SLOT_PENIS))
	fit_chastity_test_device(wearer, /obj/item/clothing/undies/chastity/cage)
	var/datum/sex_action/chastity/hands/stroke_cock/stroke = allocate(/datum/sex_action/chastity/hands/stroke_cock)
	TEST_ASSERT(stroke.shows_on_menu(user, wearer), "Chastity play should show by default.")
	user.set_cached_erp_preferences(list(/datum/erp_preference/boolean/allow_chastity_play = FALSE))
	TEST_ASSERT(!stroke.shows_on_menu(user, wearer), "An opted-out user should not see chastity play.")
	TEST_ASSERT(!stroke.can_perform(user, wearer), "An opted-out user should not do chastity play.")

/datum/unit_test/chastity_actions_keep_partner_organs_gated/Run()
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human)
	var/mob/living/carbon/human/wearer = allocate(/mob/living/carbon/human)
	give_chastity_test_organs(user, list(ORGAN_SLOT_PENIS, ORGAN_SLOT_VAGINA))
	give_chastity_test_organs(wearer, list(ORGAN_SLOT_PENIS))
	fit_chastity_test_device(wearer, /obj/item/clothing/undies/chastity/cage)
	var/datum/sex_action/chastity/ride_cage/ride = allocate(/datum/sex_action/chastity/ride_cage)
	var/datum/sex_action/chastity/cage_to_cage/grind = allocate(/datum/sex_action/chastity/cage_to_cage)
	var/datum/sex_action/chastity/frot_on_cage/frot_on = allocate(/datum/sex_action/chastity/frot_on_cage)
	TEST_ASSERT_NULL(ride.get_blocked_organ_slot(user, wearer), "A bare pussy should ride freely.")
	TEST_ASSERT(!grind.shows_on_menu(user, wearer), "Grinding cages needs a cage on both.")

	fit_chastity_test_device(user, /obj/item/clothing/undies/chastity/intersex)
	TEST_ASSERT_EQUAL(ride.get_blocked_organ_slot(user, wearer), ORGAN_SLOT_VAGINA, "A rider's own sealed pussy should block riding.")
	TEST_ASSERT(grind.shows_on_menu(user, wearer), "Two caged cocks should be offered grinding.")
	TEST_ASSERT(grind.can_perform(user, wearer), "Two caged cocks should grind.")
	var/mob/living/carbon/human/bare = allocate(/mob/living/carbon/human)
	give_chastity_test_organs(bare, list(ORGAN_SLOT_PENIS))
	TEST_ASSERT(!grind.shows_on_menu(user, bare), "A caged user should not grind cages with a bare partner.")
	TEST_ASSERT(!grind.can_perform(user, bare), "Grinding cages needs the partner caged too.")
	TEST_ASSERT_EQUAL(frot_on.get_blocked_organ_slot(user, wearer), ORGAN_SLOT_PENIS, "A partner's caged cock should not frot on a cage.")

/datum/unit_test/chastity_actions_run_without_runtimes/Run()
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human)
	var/mob/living/carbon/human/wearer = allocate(/mob/living/carbon/human)
	give_chastity_test_organs(user, list(ORGAN_SLOT_PENIS, ORGAN_SLOT_VAGINA, ORGAN_SLOT_ANUS))
	give_chastity_test_organs(wearer, list(ORGAN_SLOT_PENIS, ORGAN_SLOT_VAGINA, ORGAN_SLOT_ANUS))
	fit_chastity_test_device(user, /obj/item/clothing/undies/chastity/intersex)
	fit_chastity_test_device(wearer, /obj/item/clothing/undies/chastity/intersex)
	for(var/datum/sex_action/chastity/action_type as anything in subtypesof(/datum/sex_action/chastity))
		if(IS_ABSTRACT(action_type))
			continue
		var/datum/sex_action/chastity/action = allocate(action_type)
		var/mob/living/target = action.self_only ? user : wearer
		var/runtimed = FALSE
		try
			action.on_start(user, target)
			action.on_perform(user, target)
			action.on_finish(user, target)
		catch
			runtimed = TRUE
		TEST_ASSERT(!runtimed, "[action_type] should run without runtimes.")

/datum/unit_test/chastity_touch_flavor_picks_the_right_bank/Run()
	var/mob/living/carbon/human/cock_only = allocate(/mob/living/carbon/human)
	give_chastity_test_organs(cock_only, list(ORGAN_SLOT_PENIS))
	var/obj/item/clothing/undies/chastity/cage/cage = fit_chastity_test_device(cock_only, /obj/item/clothing/undies/chastity/cage)
	TEST_ASSERT_EQUAL(cage.get_touch_flavor_key(TRUE), "cock_self", "Stroking your own cage should use the self lines.")
	TEST_ASSERT_EQUAL(cage.get_touch_flavor_key(FALSE), "cock_touched", "A partner at the cage should use the touched lines.")
	var/mob/living/carbon/human/intersex = allocate(/mob/living/carbon/human)
	give_chastity_test_organs(intersex, list(ORGAN_SLOT_PENIS, ORGAN_SLOT_VAGINA))
	var/obj/item/clothing/undies/chastity/intersex/device = fit_chastity_test_device(intersex, /obj/item/clothing/undies/chastity/intersex)
	TEST_ASSERT_EQUAL(device.get_touch_flavor_key(FALSE), "intersex_touched", "An intersex device should use the intersex lines.")
	intersex.set_patron(/datum/patron/faerun/neutral_gods/Helm)
	intersex.add_quirk(/datum/quirk/vice/addiction/godfearing)
	TEST_ASSERT_EQUAL(device.get_touch_flavor_key(TRUE), "self_devout", "A devout wearer should use the devout lines.")

/datum/unit_test/chastity_action_stimulates_through_a_scene/Run()
	var/mob/living/carbon/human/wearer = allocate(/mob/living/carbon/human)
	give_chastity_test_organs(wearer, list(ORGAN_SLOT_PENIS))
	fit_chastity_test_device(wearer, /obj/item/clothing/undies/chastity/cage)
	var/datum/sex_scene_controller/controller = wearer.open_sex_scene(wearer, FALSE)
	var/datum/sex_action/chastity/hands/self_cock/action = controller.instantiate_action(/datum/sex_action/chastity/hands/self_cock)
	TEST_ASSERT(action.bind_runtime(controller), "Stroking your own cage should bind to the scene.")
	var/list/arousal_before = list()
	SEND_SIGNAL(wearer, COMSIG_SEX_GET_AROUSAL, arousal_before)
	var/runtimed = FALSE
	try
		action.on_perform(wearer, wearer)
	catch
		runtimed = TRUE
	var/list/arousal_after = list()
	SEND_SIGNAL(wearer, COMSIG_SEX_GET_AROUSAL, arousal_after)
	wearer.sex_scene?.stop_action(action)
	qdel(controller)
	TEST_ASSERT(!runtimed, "A scene-driven chastity action should not runtime.")
	TEST_ASSERT(arousal_after["arousal"] > arousal_before["arousal"], "Stroking your cage should still arouse.")
