/// Gives a test human the organs in [slots].
/datum/unit_test/proc/give_chastity_test_organs(mob/living/carbon/human/human, list/slots)
	var/static/list/organ_types = list(
		ORGAN_SLOT_PENIS = /obj/item/organ/genitals/penis,
		ORGAN_SLOT_TESTICLES = /obj/item/organ/genitals/filling_organ/testicles,
		ORGAN_SLOT_VAGINA = /obj/item/organ/genitals/filling_organ/vagina,
		ORGAN_SLOT_ANUS = /obj/item/organ/genitals/filling_organ/anus,
	)
	for(var/slot in slots)
		var/obj/item/organ/organ = allocate(organ_types[slot])
		organ.Insert(human, TRUE, FALSE)

/datum/unit_test/proc/fit_chastity_test_device(mob/living/carbon/human/human, device_type)
	var/obj/item/clothing/undies/chastity/device = allocate(device_type)
	human.equip_to_slot_if_possible(device, ITEM_SLOT_UNDER_BOTTOM, disable_warning = TRUE)
	return device

/datum/unit_test/chastity_devices_block_only_their_organs/Run()
	var/list/slots = list(ORGAN_SLOT_PENIS, ORGAN_SLOT_TESTICLES, ORGAN_SLOT_VAGINA, ORGAN_SLOT_ANUS)
	for(var/device_type in subtypesof(/obj/item/clothing/undies/chastity))
		var/mob/living/carbon/human/human = allocate(/mob/living/carbon/human)
		give_chastity_test_organs(human, slots)
		var/obj/item/clothing/undies/chastity/device = fit_chastity_test_device(human, device_type)
		TEST_ASSERT_EQUAL(human.underwear, device, "[device_type] should fit a body with every organ.")
		for(var/slot in slots)
			TEST_ASSERT_EQUAL(human.is_organ_slot_blocked(slot), !!(slot in device.blocked_organ_slots), "[device_type] blocked the wrong organs at [slot].")
		TEST_ASSERT(!human.is_organ_slot_blocked(ORGAN_SLOT_TESTICLES), "[device_type] should never block the testicles.")
		TEST_ASSERT(human.dropItemToGround(device), "An unlocked [device_type] should come off.")
		for(var/slot in slots)
			TEST_ASSERT(!human.is_organ_slot_blocked(slot), "Removing [device_type] should free [slot].")

/datum/unit_test/chastity_device_needs_matching_genitals/Run()
	var/mob/living/carbon/human/pussy_only = allocate(/mob/living/carbon/human)
	give_chastity_test_organs(pussy_only, list(ORGAN_SLOT_VAGINA))
	var/mob/living/carbon/human/cock_only = allocate(/mob/living/carbon/human)
	give_chastity_test_organs(cock_only, list(ORGAN_SLOT_PENIS))
	var/mob/living/carbon/human/bare = allocate(/mob/living/carbon/human)

	var/obj/item/clothing/undies/chastity/cage/cage = allocate(/obj/item/clothing/undies/chastity/cage)
	var/obj/item/clothing/undies/chastity/insertable/insertable = allocate(/obj/item/clothing/undies/chastity/insertable)
	var/obj/item/clothing/undies/chastity/intersex/intersex = allocate(/obj/item/clothing/undies/chastity/intersex)
	var/obj/item/clothing/undies/chastity/belt/belt = allocate(/obj/item/clothing/undies/chastity/belt)
	TEST_ASSERT(!cage.can_fit_on(pussy_only), "A cage needs a cock.")
	TEST_ASSERT(cage.can_fit_on(cock_only), "A cage should fit a cock.")
	TEST_ASSERT(!insertable.can_fit_on(cock_only), "An insertable belt needs a pussy.")
	TEST_ASSERT(insertable.can_fit_on(pussy_only), "An insertable belt should fit a pussy.")
	TEST_ASSERT(!intersex.can_fit_on(cock_only), "An intersex device needs both.")
	TEST_ASSERT(belt.can_fit_on(bare), "A plain belt should fit any body.")
	TEST_ASSERT(!cock_only.equip_to_slot_if_possible(insertable, ITEM_SLOT_UNDER_BOTTOM, disable_warning = TRUE), "Equipping should refuse a device that doesn't fit.")

/datum/unit_test/chastity_lock_keeps_device_on/Run()
	var/mob/living/carbon/human/human = allocate(/mob/living/carbon/human)
	var/mob/living/carbon/human/stripper = allocate(/mob/living/carbon/human)
	give_chastity_test_organs(human, list(ORGAN_SLOT_PENIS))
	var/obj/item/clothing/undies/chastity/cage/cage = fit_chastity_test_device(human, /obj/item/clothing/undies/chastity/cage)
	cage.lock.lock()
	TEST_ASSERT(cage.locked(), "The cage should lock.")
	TEST_ASSERT(!human.dropItemToGround(cage), "A locked cage should stay on.")
	TEST_ASSERT_EQUAL(human.underwear, cage, "A locked cage should still be worn.")
	TEST_ASSERT(!cage.canStrip(stripper, human), "A locked cage should not be strippable.")

	give_chastity_test_organs(stripper, list(ORGAN_SLOT_PENIS))
	var/obj/item/clothing/undies/chastity/cage/spare = allocate(/obj/item/clothing/undies/chastity/cage)
	TEST_ASSERT(spare.can_fit_on(stripper), "An open spare cage should fit a cock.")
	spare.lock.lock()
	TEST_ASSERT(!spare.can_fit_on(stripper), "A locked device should not fit anyone.")

	cage.lock.unlock()
	TEST_ASSERT(cage.canStrip(stripper, human), "An unlocked cage should be strippable.")
	TEST_ASSERT(human.dropItemToGround(cage), "An unlocked cage should come off.")

/datum/unit_test/chastity_key_access_and_hard_mode/Run()
	var/mob/living/carbon/human/human = allocate(/mob/living/carbon/human)
	give_chastity_test_organs(human, list(ORGAN_SLOT_PENIS))
	var/obj/item/clothing/undies/chastity/cage/cage = fit_chastity_test_device(human, /obj/item/clothing/undies/chastity/cage)
	var/datum/lock/key/chastity/cage_lock = cage.lock
	cage_lock.lock()
	var/obj/item/key/chastity/key = cage.get_generated_key()
	TEST_ASSERT_NOTNULL(key, "A device should come with its own key.")
	var/obj/item/key/copy = allocate(/obj/item/key)
	copy.lockids = key.lockids.Copy()
	var/obj/item/key/master = allocate(/obj/item/key)
	master.lockids = list(ACCESS_LORD)
	var/obj/item/storage/keyring/keyring = allocate(/obj/item/storage/keyring)
	key.forceMove(keyring)

	TEST_ASSERT(cage_lock.check_access(key), "The device's own key should fit.")
	TEST_ASSERT(cage_lock.check_access(copy), "A copied key should fit outside hard mode.")
	TEST_ASSERT(cage_lock.check_access(master), "A master key should fit outside hard mode.")
	TEST_ASSERT(cage.can_be_picked(), "A locked device should be pickable outside hard mode.")

	human.set_cached_erp_preferences(list(/datum/erp_preference/boolean/chastity_hardmode = TRUE))
	TEST_ASSERT(cage.is_hardmode_active(), "The wearer's hard mode pref should count.")
	TEST_ASSERT(cage_lock.check_access(key), "Hard mode should still accept the device's own key.")
	TEST_ASSERT(cage_lock.check_access(keyring), "Hard mode should accept a keyring holding the key.")
	TEST_ASSERT(!cage_lock.check_access(copy), "Hard mode should refuse a copied key.")
	TEST_ASSERT(!cage_lock.check_access(master), "Hard mode should refuse the master key.")
	TEST_ASSERT(!cage.can_be_picked(), "Hard mode should refuse lockpicks.")

/datum/unit_test/chastity_chisel_breaks_lock_without_harm/Run()
	var/mob/living/carbon/human/human = allocate(/mob/living/carbon/human)
	var/mob/living/carbon/human/smith = allocate(/mob/living/carbon/human)
	give_chastity_test_organs(human, list(ORGAN_SLOT_PENIS))
	var/obj/item/clothing/undies/chastity/cage/cage = fit_chastity_test_device(human, /obj/item/clothing/undies/chastity/cage)
	cage.lock.lock()
	var/obj/item/weapon/chisel/chisel = allocate(/obj/item/weapon/chisel)
	var/obj/item/weapon/hammer/hammer = allocate(/obj/item/weapon/hammer)
	smith.put_in_active_hand(chisel, forced = TRUE)
	smith.put_in_inactive_hand(hammer)
	TEST_ASSERT(cage.can_chisel(smith, chisel), "A chisel and hammer should be able to work the lock.")

	human.set_cached_erp_preferences(list(/datum/erp_preference/boolean/chastity_hardmode = TRUE))
	TEST_ASSERT(!cage.can_chisel(smith, chisel), "Hard mode should refuse the chisel.")
	human.set_cached_erp_preferences(list(/datum/erp_preference/boolean/chastity_hardmode = FALSE))

	var/brute_before = human.getBruteLoss()
	cage.break_lock(smith)
	TEST_ASSERT_NULL(human.underwear, "A broken lock should free the wearer.")
	TEST_ASSERT(isturf(cage.loc), "With both hands on the tools, the freed device should fall to the floor.")
	TEST_ASSERT_EQUAL(human.getBruteLoss(), brute_before, "Chiselling should never hurt the wearer.")
	var/datum/lock/key/chastity/cage_lock = cage.lock
	cage_lock.try_toggle(smith, cage.get_generated_key(), FALSE)
	TEST_ASSERT(!cage.locked(), "A broken lock should never close again.")

/datum/unit_test/chastity_release_frees_locked_wearer/Run()
	var/mob/living/carbon/human/human = allocate(/mob/living/carbon/human)
	var/obj/item/clothing/undies/chastity/belt/belt = fit_chastity_test_device(human, /obj/item/clothing/undies/chastity/belt)
	belt.lock.lock()
	TEST_ASSERT(human.release_chastity_device(), "Release should work on a locked device.")
	TEST_ASSERT_NULL(human.underwear, "Release should take the device off.")
	TEST_ASSERT(!belt.locked(), "A released device should be unlocked.")

/datum/unit_test/chastity_shield_blocks_anal_actions/Run()
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human)
	var/mob/living/carbon/human/target = allocate(/mob/living/carbon/human)
	give_chastity_test_organs(target, list(ORGAN_SLOT_PENIS, ORGAN_SLOT_ANUS))
	var/datum/sex_action/rimming/rim = allocate(/datum/sex_action/rimming)
	var/datum/sex_action/masturbate/anus/finger = allocate(/datum/sex_action/masturbate/anus)
	var/datum/sex_action/masturbate/penis/stroke = allocate(/datum/sex_action/masturbate/penis)

	var/obj/item/clothing/undies/chastity/cage/cage = fit_chastity_test_device(target, /obj/item/clothing/undies/chastity/cage)
	TEST_ASSERT_NULL(rim.get_blocked_organ_slot(user, target), "A plain cage should leave the rear free.")
	TEST_ASSERT_EQUAL(stroke.get_blocked_organ_slot(target, target), ORGAN_SLOT_PENIS, "A cage should block stroking.")
	target.dropItemToGround(cage)

	fit_chastity_test_device(target, /obj/item/clothing/undies/chastity/cage/shield)
	TEST_ASSERT_EQUAL(rim.get_blocked_organ_slot(user, target), ORGAN_SLOT_ANUS, "An anal shield should block rimming.")
	TEST_ASSERT_EQUAL(finger.get_blocked_organ_slot(target, target), ORGAN_SLOT_ANUS, "An anal shield should block fingering yourself.")

/datum/unit_test/chastity_hides_covered_organ_sprites/Run()
	var/mob/living/carbon/human/human = allocate(/mob/living/carbon/human)
	give_chastity_test_organs(human, list(ORGAN_SLOT_PENIS, ORGAN_SLOT_TESTICLES))
	var/obj/item/organ/genitals/penis/penis = human.getorganslot(ORGAN_SLOT_PENIS)
	var/obj/item/organ/genitals/testicles = human.getorganslot(ORGAN_SLOT_TESTICLES)
	penis.accessory_type = /datum/sprite_accessory/genitals/penis/human
	penis.visible_through_clothes = DRAW_ABOVE
	var/datum/sprite_accessory/penis_accessory = SPRITE_ACCESSORY(/datum/sprite_accessory/genitals/penis/human)
	var/datum/sprite_accessory/ball_accessory = SPRITE_ACCESSORY(/datum/sprite_accessory/genitals/testicles/pair)
	var/bare_key = human.generate_icon_render_key()
	TEST_ASSERT(penis_accessory.is_visible(penis, null, human), "A bare cock set to show should be visible.")

	var/obj/item/clothing/undies/chastity/cage/cage = fit_chastity_test_device(human, /obj/item/clothing/undies/chastity/cage)
	TEST_ASSERT(!penis_accessory.is_visible(penis, null, human), "A cage should hide the cock even when it draws over clothes.")
	TEST_ASSERT(ball_accessory.is_visible(testicles, null, human), "A cage should leave the balls visible.")
	TEST_ASSERT_NOTEQUAL(human.generate_icon_render_key(), bare_key, "A caged cock should change the render key.")
	human.dropItemToGround(cage)

	testicles.visible_through_clothes = DRAW_ABOVE
	fit_chastity_test_device(human, /obj/item/clothing/undies/chastity/belt)
	TEST_ASSERT(!ball_accessory.is_visible(testicles, null, human), "A belt should hide the balls even when they draw over clothes.")

/datum/unit_test/chastity_leech_refuses_covered_organ/Run()
	var/mob/living/carbon/human/human = allocate(/mob/living/carbon/human)
	give_chastity_test_organs(human, list(ORGAN_SLOT_PENIS))
	var/obj/item/organ/penis = human.getorganslot(ORGAN_SLOT_PENIS)
	var/obj/item/natural/worms/leech/erotic/leech = allocate(/obj/item/natural/worms/leech/erotic)
	TEST_ASSERT(leech.can_attach_to_organ(human, penis), "A leech should latch onto a bare cock.")
	fit_chastity_test_device(human, /obj/item/clothing/undies/chastity/cage)
	TEST_ASSERT(!leech.can_attach_to_organ(human, penis), "A leech should not latch onto a caged cock.")

/datum/unit_test/chastity_quirk_locks_the_chosen_device/Run()
	var/mob/living/carbon/human/human = allocate(/mob/living/carbon/human)
	give_chastity_test_organs(human, list(ORGAN_SLOT_PENIS))
	TEST_ASSERT(human.add_quirk(/datum/quirk/peculiarity/kept_in_chastity, "[/obj/item/clothing/undies/chastity/cage]"), "The quirk should apply.")
	var/datum/quirk/peculiarity/kept_in_chastity/quirk = locate() in human.quirks
	quirk.after_job_spawn(null)
	TEST_ASSERT(istype(human.underwear, /obj/item/clothing/undies/chastity/cage), "The quirk should fit the chosen cage.")
	TEST_ASSERT(human.underwear.locked(), "The quirk's device should start locked.")
	var/obj/item/key/chastity/key = locate() in human.held_items
	TEST_ASSERT_NOTNULL(key, "The key should be on the wearer.")

	var/mob/living/carbon/human/lost = allocate(/mob/living/carbon/human)
	give_chastity_test_organs(lost, list(ORGAN_SLOT_PENIS))
	lost.add_quirk(/datum/quirk/peculiarity/kept_in_chastity, "[/obj/item/clothing/undies/chastity/cage]", list("key" = "Lost"))
	var/datum/quirk/peculiarity/kept_in_chastity/lost_quirk = locate() in lost.quirks
	lost_quirk.after_job_spawn(null)
	TEST_ASSERT(lost.underwear?.locked(), "A lost-key wearer should still be locked in.")
	TEST_ASSERT_NULL((locate(/obj/item/key/chastity) in lost.held_items), "A lost key should not be carried.")

	var/mob/living/carbon/human/mismatch = allocate(/mob/living/carbon/human)
	give_chastity_test_organs(mismatch, list(ORGAN_SLOT_PENIS))
	mismatch.add_quirk(/datum/quirk/peculiarity/kept_in_chastity, "[/obj/item/clothing/undies/chastity/insertable]")
	var/datum/quirk/peculiarity/kept_in_chastity/mismatch_quirk = locate() in mismatch.quirks
	mismatch_quirk.after_job_spawn(null)
	TEST_ASSERT_NULL(mismatch.underwear, "A device that doesn't fit should not be worn.")
	TEST_ASSERT_NOTNULL((locate(/obj/item/clothing/undies/chastity/insertable) in mismatch.held_items), "A device that doesn't fit should be carried.")

/datum/unit_test/chastity_sprites_exist/Run()
	var/list/item_states = icon_states('modular_rmh/icons/obj/lewd/chastity.dmi')
	var/list/worn_states = icon_states('modular_rmh/icons/obj/lewd/chastity_onmob.dmi')
	for(var/obj/item/clothing/undies/chastity/device_type as anything in subtypesof(/obj/item/clothing/undies/chastity))
		var/state = initial(device_type.icon_state)
		TEST_ASSERT(state in item_states, "[device_type] is missing item state [state].")
		for(var/suffix in list("", "_f", "_dwarf", "_f_dwarf"))
			TEST_ASSERT("[state][suffix]" in worn_states, "[device_type] is missing worn state [state][suffix].")
