/proc/get_pump_test_arousal(mob/living/living_mob, key = "arousal")
	var/list/arousal_data = list()
	SEND_SIGNAL(living_mob, COMSIG_SEX_GET_AROUSAL, arousal_data)
	return arousal_data[key]

/datum/unit_test/fluid_pump_fits_over_its_organ_and_covers_it/Run()
	var/mob/living/carbon/human/human = allocate(/mob/living/carbon/human)
	var/obj/item/organ/genitals/filling_organ/breasts/breasts = allocate(/obj/item/organ/genitals/filling_organ/breasts)
	breasts.Insert(human, TRUE, FALSE)
	var/obj/item/reagent_containers/glass/fluid_pump/breast/pump = allocate(/obj/item/reagent_containers/glass/fluid_pump/breast)
	TEST_ASSERT(!human.is_organ_slot_blocked(ORGAN_SLOT_BREASTS), "Bare breasts should be free.")
	TEST_ASSERT(!pump.can_enter_body_storage_layer(STORAGE_LAYER_INNER), "A pump should only fit over an opening.")
	TEST_ASSERT(!SEND_SIGNAL(breasts, COMSIG_BODYSTORAGE_TRY_INSERT, pump, STORAGE_LAYER_INNER, FALSE), "Storing a pump inside should fail.")

	var/result = pump.attach_to(human)
	TEST_ASSERT(result == INSERT_FEEDBACK_OK || result == INSERT_FEEDBACK_ALMOST_FULL, "The pump should fit over breasts, got [result].")
	TEST_ASSERT_EQUAL(pump.attached_organ, breasts, "The pump should know the organ it covers.")
	TEST_ASSERT(human.is_organ_slot_blocked(ORGAN_SLOT_BREASTS), "A fitted pump should cover the breasts.")
	TEST_ASSERT_EQUAL(breasts.get_reagent_capacity(), breasts.get_base_capacity(), "A pump should take no room inside the organ.")
	var/obj/item/natural/fibers/fibers = allocate(/obj/item/natural/fibers)
	TEST_ASSERT_EQUAL(SEND_SIGNAL(breasts, COMSIG_BODYSTORAGE_TRY_INSERT, fibers, STORAGE_LAYER_INNER, FALSE), INSERT_FEEDBACK_BLOCKED, "Nothing should go in past a pump.")

	TEST_ASSERT(pump.detach(human), "The pump should come off.")
	TEST_ASSERT(!human.is_organ_slot_blocked(ORGAN_SLOT_BREASTS), "Removing the pump should free the breasts.")
	TEST_ASSERT(human.is_holding(pump), "The removed pump should land in hand.")

/datum/unit_test/fluid_pump_draws_until_full/Run()
	var/mob/living/carbon/human/human = allocate(/mob/living/carbon/human)
	var/obj/item/organ/genitals/filling_organ/breasts/breasts = allocate(/obj/item/organ/genitals/filling_organ/breasts)
	breasts.Insert(human, TRUE, FALSE)
	breasts.reagents.clear_reagents()
	breasts.reagents.add_reagent(/datum/reagent/consumable/milk, 50)
	var/obj/item/reagent_containers/glass/fluid_pump/breast/pump = allocate(/obj/item/reagent_containers/glass/fluid_pump/breast)
	pump.attach_to(human)

	pump.process(2)
	TEST_ASSERT(abs(pump.reagents.get_reagent_amount(/datum/reagent/consumable/milk) - 2) < 0.01, "The breast pump should draw a unit of milk a second.")
	TEST_ASSERT(abs(breasts.reagents.total_volume - 48) < 0.01, "The milk should leave the breasts.")
	TEST_ASSERT_EQUAL(get_pump_test_arousal(human, "orgasm_progress"), 0, "A breast pump should not push toward climax.")

	pump.reagents.add_reagent(/datum/reagent/water, pump.volume)
	SEND_SIGNAL(human, COMSIG_SEX_SET_AROUSAL, 0)
	pump.process(2)
	TEST_ASSERT(abs(breasts.reagents.total_volume - 48) < 0.01, "A full pump should stop drawing.")
	TEST_ASSERT_EQUAL(get_pump_test_arousal(human), 0, "A full pump should stop working on its wearer.")

	pump.reagents.clear_reagents()
	pump.reagents.add_reagent(/datum/reagent/water, 10)
	breasts.exchange_with_stored_containers()
	TEST_ASSERT_EQUAL(pump.reagents.get_reagent_amount(/datum/reagent/water), 10, "The organ should never pour a pump's catch back in.")

/datum/unit_test/fluid_pump_milker_pushes_to_climax_and_catches_it/Run()
	var/mob/living/carbon/human/human = allocate(/mob/living/carbon/human)
	var/obj/item/organ/genitals/penis/penis = allocate(/obj/item/organ/genitals/penis)
	penis.Insert(human, TRUE, FALSE)
	var/obj/item/organ/genitals/filling_organ/testicles/testicles = allocate(/obj/item/organ/genitals/filling_organ/testicles)
	testicles.Insert(human, TRUE, FALSE)
	testicles.reagents.clear_reagents()
	testicles.reagents.add_reagent(/datum/reagent/consumable/cum, testicles.reagents.maximum_volume)
	var/full_balls = testicles.reagents.total_volume
	var/obj/item/reagent_containers/glass/fluid_pump/cock/milker = allocate(/obj/item/reagent_containers/glass/fluid_pump/cock)
	milker.attach_to(human)
	TEST_ASSERT(human.is_organ_slot_blocked(ORGAN_SLOT_PENIS), "The milker should cover the cock.")

	SEND_SIGNAL(human, COMSIG_SEX_SET_AROUSAL, 0)
	milker.process(2)
	TEST_ASSERT(get_pump_test_arousal(human) > 0, "The milker should arouse its wearer.")
	TEST_ASSERT(get_pump_test_arousal(human, "orgasm_progress") > 0, "The milker should push toward climax.")
	TEST_ASSERT_EQUAL(testicles.reagents.total_volume, full_balls, "The milker should not drain the balls without a climax.")

	var/datum/component/arousal/arousal = human.GetComponent(/datum/component/arousal)
	TEST_ASSERT_NOTNULL(arousal, "Humans should have an arousal component.")
	var/runtimed = FALSE
	try
		arousal.ejaculate()
	catch
		runtimed = TRUE
	TEST_ASSERT(!runtimed, "A hands-free climax should not runtime.")
	TEST_ASSERT(milker.reagents.get_reagent_amount(/datum/reagent/consumable/cum) > 0, "The milker should catch a hands-free climax.")
	TEST_ASSERT_EQUAL(testicles.get_leak_pump(), milker, "Leaking balls should drip into the milker on the cock.")
	var/datum/sex_action_effect_context/context = new(human, human, null, human, human)
	context.climaxer = human
	var/datum/reagents/stranger = new /datum/reagents(20)
	stranger.add_reagent(/datum/reagent/consumable/cum, 20)
	TEST_ASSERT_EQUAL(milker.catch_climax(context, stranger, 10), 0, "The milker should only catch its own wearer's seed.")
	qdel(stranger)
	milker.reagents.clear_reagents()
	testicles.reagents.add_reagent(/datum/reagent/consumable/cum, 20)
	testicles.reagents.maximum_volume = testicles.reagents.total_volume / 2
	testicles.leak_reagents()
	TEST_ASSERT(milker.reagents.total_volume > 0, "Overfull balls should leak into the milker.")

/datum/unit_test/fluid_pump_blocks_actions_on_its_organ/Run()
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human)
	var/mob/living/carbon/human/target = allocate(/mob/living/carbon/human)
	var/obj/item/organ/genitals/penis/penis = allocate(/obj/item/organ/genitals/penis)
	penis.Insert(user, TRUE, FALSE)
	var/obj/item/organ/genitals/filling_organ/vagina/user_vagina = allocate(/obj/item/organ/genitals/filling_organ/vagina)
	user_vagina.Insert(user, TRUE, FALSE)
	var/obj/item/organ/genitals/filling_organ/vagina/vagina = allocate(/obj/item/organ/genitals/filling_organ/vagina)
	vagina.Insert(target, TRUE, FALSE)
	var/datum/sex_action/cunnilingus/lick = allocate(/datum/sex_action/cunnilingus)
	var/datum/sex_action/sex/vaginal/fuck = allocate(/datum/sex_action/sex/vaginal)
	var/datum/sex_action/masturbate/penis/stroke = allocate(/datum/sex_action/masturbate/penis)
	TEST_ASSERT_NULL(fuck.get_blocked_organ_slot(user, target), "Nothing should block bare genitals.")

	var/obj/item/reagent_containers/glass/fluid_pump/vagina/cup = allocate(/obj/item/reagent_containers/glass/fluid_pump/vagina)
	cup.attach_to(target)
	TEST_ASSERT_EQUAL(lick.get_blocked_organ_slot(user, target), ORGAN_SLOT_VAGINA, "A pump should block licking the pussy it covers.")
	TEST_ASSERT_EQUAL(fuck.get_blocked_organ_slot(user, target), ORGAN_SLOT_VAGINA, "A pump should block fucking the pussy it covers.")
	cup.detach(target)
	TEST_ASSERT_NULL(fuck.get_blocked_organ_slot(user, target), "Removing the pump should free the pussy.")

	var/obj/item/reagent_containers/glass/fluid_pump/cock/milker = allocate(/obj/item/reagent_containers/glass/fluid_pump/cock)
	milker.attach_to(user)
	TEST_ASSERT_EQUAL(fuck.get_blocked_organ_slot(user, target), ORGAN_SLOT_PENIS, "A milker should block fucking with the cock it covers.")
	TEST_ASSERT_EQUAL(stroke.get_blocked_organ_slot(user, user), ORGAN_SLOT_PENIS, "A milker should block stroking the cock it covers.")
	TEST_ASSERT(!stroke.can_perform(user, user), "A covered cock should not be strokable.")
	TEST_ASSERT(!stroke.can_continue(user, user), "Fitting a milker should end stroking.")
	TEST_ASSERT_NULL(stroke.get_free_organ(user, ORGAN_SLOT_PENIS), "A covered cock should not count as free.")
	TEST_ASSERT_EQUAL(stroke.get_free_organ(user, ORGAN_SLOT_VAGINA), user_vagina, "A futa's bare pussy should stay free.")
	milker.detach(user)
	TEST_ASSERT(stroke.can_perform(user, user), "A bare cock should be strokable again.")

/datum/unit_test/fluid_pump_actions_fit_and_remove/Run()
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human)
	var/mob/living/carbon/human/target = allocate(/mob/living/carbon/human)
	var/obj/item/organ/genitals/filling_organ/breasts/breasts = allocate(/obj/item/organ/genitals/filling_organ/breasts)
	breasts.Insert(target, TRUE, FALSE)
	var/obj/item/reagent_containers/glass/fluid_pump/breast/pump = allocate(/obj/item/reagent_containers/glass/fluid_pump/breast)
	var/datum/sex_action/attach_fluid_pump/attach = allocate(/datum/sex_action/attach_fluid_pump)
	var/datum/sex_action/remove_fluid_pump/remove = allocate(/datum/sex_action/remove_fluid_pump)
	TEST_ASSERT(!attach.shows_on_menu(user, target), "Empty hands should not offer a pump.")

	TEST_ASSERT(user.put_in_active_hand(pump, forced = TRUE), "The user should hold the pump.")
	TEST_ASSERT(attach.shows_on_menu(user, target), "A held pump should offer fitting it.")
	TEST_ASSERT(attach.can_perform(user, target), "A held pump should fit bare breasts.")
	attach.on_perform(user, target)
	TEST_ASSERT_EQUAL(pump.attached_organ, breasts, "The action should fit the pump.")
	TEST_ASSERT(!user.is_holding(pump), "A fitted pump should leave the hand.")
	TEST_ASSERT(remove.shows_on_menu(user, target), "A fitted pump should offer removing it.")

	remove.on_perform(user, target)
	TEST_ASSERT_NULL(pump.attached_organ, "The action should remove the pump.")
	TEST_ASSERT(user.is_holding(pump), "The removed pump should land in the remover's hand.")

/datum/unit_test/fluid_pump_sprites_exist/Run()
	var/list/item_states = icon_states('modular_rmh/icons/obj/lewd/fluid_pumps.dmi')
	var/list/overlay_states = icon_states('modular_rmh/icons/obj/lewd/fluid_pumps_overlay.dmi')
	for(var/pump_type in subtypesof(/obj/item/reagent_containers/glass/fluid_pump))
		var/obj/item/reagent_containers/glass/fluid_pump/pump = pump_type
		var/state = initial(pump.icon_state)
		TEST_ASSERT(state in item_states, "[pump_type] should have an item sprite.")
		TEST_ASSERT(state in overlay_states, "[pump_type] should have a body overlay.")
	for(var/level in 1 to 3)
		TEST_ASSERT("pump_fill[level]" in item_states, "The reservoir should have fill level [level].")
