/// A minded adult test human with one fertile womb and the given antagonist-pregnancy preference.
/proc/make_gnoll_test_carrier(datum/unit_test/test, allow_pregnancy = TRUE)
	var/mob/living/carbon/human/carrier = test.allocate(/mob/living/carbon/human)
	carrier.age = AGE_ADULT
	carrier.mind_initialize()
	if(!carrier.getorganslot(ORGAN_SLOT_VAGINA))
		var/obj/item/organ/genitals/filling_organ/vagina/vagina = new
		vagina.Insert(carrier, TRUE, FALSE)
	carrier.set_cached_erp_preferences(list(/datum/erp_preference/boolean/antag_pregnancy = allow_pregnancy))
	return carrier

/datum/unit_test/gnoll_champion_setup/Run()
	var/mob/living/carbon/human/body = allocate(/mob/living/carbon/human)
	body.mind_initialize()
	var/datum/antagonist/gnoll/champion = body.mind.add_antag_datum(/datum/antagonist/gnoll)
	TEST_ASSERT_NOTNULL(champion, "A human with a mind should become a gnoll champion.")
	TEST_ASSERT_NOTNULL(champion.pack, "A champion should join a pack.")
	TEST_ASSERT(istype(body.dna.species, /datum/species/gnoll_champion), "A champion should take the champion species.")
	TEST_ASSERT(istype(body.skin_armor, /obj/item/clothing/armor/regenerating/skin/gnoll), "A champion should grow a pelt.")
	var/has_claws = FALSE
	for(var/datum/action/cooldown/spell/undirected/gnoll_claws/claws in body.actions)
		has_claws = TRUE
	TEST_ASSERT(has_claws, "A champion should get the claws ability.")
	var/datum/team/gnoll/pack = champion.pack
	body.mind.remove_antag_datum(/datum/antagonist/gnoll)
	qdel(pack)

/datum/unit_test/gnoll_captive_rules/Run()
	var/datum/team/gnoll/pack = allocate(/datum/team/gnoll)
	var/mob/living/carbon/human/captive = make_gnoll_test_carrier(src)
	TEST_ASSERT(!is_gnoll_captive(captive, require_client = FALSE), "A free person should not count as captive.")
	ADD_TRAIT(captive, TRAIT_RESTRAINED, TRAIT_GENERIC)
	TEST_ASSERT(is_gnoll_captive(captive, require_client = FALSE), "A restrained person should count as captive.")
	TEST_ASSERT(can_carry_gnoll_renewal(captive, pack, require_client = FALSE), "A restrained, opted-in person with a womb should qualify.")

	captive.set_cached_erp_preferences(list(/datum/erp_preference/boolean/antag_pregnancy = FALSE))
	TEST_ASSERT(!can_carry_gnoll_renewal(captive, pack, require_client = FALSE), "Without the antag pregnancy preference the captive should not qualify.")

	captive.set_cached_erp_preferences(list(/datum/erp_preference/boolean/antag_pregnancy = TRUE))
	pack.ritual_carriers += REF(captive.mind)
	TEST_ASSERT(!can_carry_gnoll_renewal(captive, pack, require_client = FALSE), "A carrier should carry the pack's renewal only once.")
	REMOVE_TRAIT(captive, TRAIT_RESTRAINED, TRAIT_GENERIC)

/datum/unit_test/gnoll_conception_and_remedy/Run()
	var/datum/team/gnoll/pack = allocate(/datum/team/gnoll)
	var/mob/living/carbon/human/carrier = make_gnoll_test_carrier(src)
	var/mob/living/carbon/human/father = allocate(/mob/living/carbon/human)
	TEST_ASSERT_NOTNULL(get_gnoll_ritual_womb(carrier), "The test carrier should have a usable womb.")

	var/datum/status_effect/gnoll_fertility_mark/mark = carrier.apply_status_effect(/datum/status_effect/gnoll_fertility_mark, pack)
	TEST_ASSERT_NOTNULL(mark, "The fertility rite should mark the carrier.")
	TEST_ASSERT(mark.conceive(father), "A marked carrier should conceive.")
	TEST_ASSERT_NULL(carrier.has_status_effect(/datum/status_effect/gnoll_fertility_mark), "Conception should use up the mark.")
	TEST_ASSERT_NOTNULL(get_gnoll_ritual_pregnancy(carrier), "Conception should start the ritual pregnancy.")
	TEST_ASSERT(REF(carrier.mind) in pack.ritual_carriers, "The pack should remember its carrier.")

	carrier.reagents.add_reagent(/datum/reagent/medicine/antipregnancy, 5)
	carrier.reagents.metabolize(carrier)
	TEST_ASSERT_NULL(get_gnoll_ritual_pregnancy(carrier), "The pregnancy removal potion should end the ritual pregnancy.")

/datum/unit_test/egg_pregnancy_blocks_conventional/Run()
	var/mob/living/carbon/human/carrier = make_gnoll_test_carrier(src)
	var/mob/living/carbon/human/father = allocate(/mob/living/carbon/human)
	var/obj/item/organ/genitals/filling_organ/vagina/womb = carrier.getorganslot(ORGAN_SLOT_VAGINA)
	var/obj/item/oviposition_egg/egg = new
	egg.set_oviposition_mother(carrier)
	SEND_SIGNAL(womb, COMSIG_BODYSTORAGE_TRY_INSERT, egg, STORAGE_LAYER_DEEP)
	TEST_ASSERT(womb.is_oviposition_egg(egg), "The test egg should sit in the womb.")
	TEST_ASSERT(womb.be_impregnated(father), "Seed should fertilize the hosted egg.")
	TEST_ASSERT(womb.has_oviposition_pregnancy(), "The fertilized egg should be growing.")
	TEST_ASSERT(!womb.can_attempt_impregnation(), "A growing egg should refuse a conventional pregnancy.")
	TEST_ASSERT(!womb.be_impregnated(father), "A growing egg should not let a conventional pregnancy start.")
	TEST_ASSERT(!womb.pregnant, "No conventional pregnancy should start beside the egg.")

/datum/unit_test/gnoll_embryo_blocks_conception/Run()
	var/datum/team/gnoll/pack = allocate(/datum/team/gnoll)
	var/mob/living/carbon/human/carrier = make_gnoll_test_carrier(src)
	var/mob/living/carbon/human/father = allocate(/mob/living/carbon/human)
	var/obj/item/organ/genitals/filling_organ/vagina/womb = get_gnoll_ritual_womb(carrier)
	TEST_ASSERT_NOTNULL(womb, "The test carrier should have a usable womb.")
	TEST_ASSERT(start_gnoll_ritual_pregnancy(carrier, father, pack, womb), "The ritual embryo should take.")
	TEST_ASSERT(!womb.be_impregnated(father), "The ritual embryo should refuse a conventional pregnancy.")

	var/obj/item/organ/genitals/filling_organ/testicles/testicles = new
	testicles.Insert(father, TRUE, FALSE)
	testicles.reagents.clear_reagents()
	testicles.reagents.add_reagent(/datum/reagent/consumable/cum, 10)
	testicles.sync_cum_source_data()
	testicles.reagents.trans_to(womb, 10, transfered_by = father, method = INGEST)
	TEST_ASSERT(womb.get_virile_seed_units() >= CONCEPTION_MIN_SEED, "Enough seed should stay inside to roll.")
	carrier.reagents.add_reagent(/datum/reagent/medicine/pregplus, 5)
	TEST_ASSERT(!womb.roll_conception(), "Even certain seed should not conceive beside the ritual embryo.")
	TEST_ASSERT(!womb.pregnant, "No hidden pregnancy should start beside the ritual embryo.")
	TEST_ASSERT_NOTNULL(get_gnoll_ritual_pregnancy(carrier), "The ritual embryo should still grow.")

/datum/unit_test/egg_pregnancy_starts_during_conventional/Run()
	var/datum/team/gnoll/pack = allocate(/datum/team/gnoll)
	var/mob/living/carbon/human/carrier = make_gnoll_test_carrier(src)
	var/mob/living/carbon/human/father = allocate(/mob/living/carbon/human)
	var/obj/item/organ/genitals/filling_organ/vagina/womb = carrier.getorganslot(ORGAN_SLOT_VAGINA)
	TEST_ASSERT(womb.be_impregnated(father), "The test setup should start a conventional pregnancy.")
	TEST_ASSERT(womb.can_start_fertilization_embryo_pregnancy(TRUE), "An embryo should still be able to start.")
	TEST_ASSERT_NOTNULL(get_gnoll_ritual_womb(carrier), "A conventional pregnancy should not refuse the ritual.")
	TEST_ASSERT(start_gnoll_ritual_pregnancy(carrier, father, pack, womb), "The ritual embryo should take beside it.")
	TEST_ASSERT(womb.pregnant, "The ritual embryo should not end the conventional pregnancy.")
	TEST_ASSERT_NOTNULL(get_gnoll_ritual_pregnancy(carrier), "Both pregnancies should be underway.")

/datum/unit_test/gnoll_conception_needs_preference/Run()
	var/datum/team/gnoll/pack = allocate(/datum/team/gnoll)
	var/mob/living/carbon/human/carrier = make_gnoll_test_carrier(src, allow_pregnancy = FALSE)
	var/mob/living/carbon/human/father = allocate(/mob/living/carbon/human)
	var/datum/status_effect/gnoll_fertility_mark/mark = carrier.apply_status_effect(/datum/status_effect/gnoll_fertility_mark, pack)
	TEST_ASSERT_NOTNULL(mark, "The mark itself should apply.")
	TEST_ASSERT(!mark.conceive(father), "A carrier without the preference should not conceive.")
	TEST_ASSERT_NULL(get_gnoll_ritual_pregnancy(carrier), "No ritual pregnancy should start without the preference.")

/datum/unit_test/gnoll_release_outside_camp/Run()
	var/datum/team/gnoll/pack = allocate(/datum/team/gnoll)
	var/mob/living/carbon/human/carrier = make_gnoll_test_carrier(src)
	TEST_ASSERT(!is_in_gnoll_camp(carrier), "The test room should not be the gnoll camp.")
	var/datum/status_effect/gnoll_owed_release/owed = carrier.apply_status_effect(/datum/status_effect/gnoll_owed_release, pack)
	TEST_ASSERT_NOTNULL(owed, "A carrier should be owed release after the birth.")
	owed.tick()
	TEST_ASSERT_NULL(carrier.has_status_effect(/datum/status_effect/gnoll_owed_release), "A carrier outside the camp should count as released.")

/datum/unit_test/gnoll_bond_breaks_on_escape/Run()
	var/datum/team/gnoll/pack = allocate(/datum/team/gnoll)
	var/mob/living/carbon/human/first = allocate(/mob/living/carbon/human)
	var/mob/living/carbon/human/second = allocate(/mob/living/carbon/human)
	var/datum/status_effect/gnoll_bond/bond = first.apply_status_effect(/datum/status_effect/gnoll_bond, second, pack)
	TEST_ASSERT_NOTNULL(bond, "The bond should apply to the first partner.")
	TEST_ASSERT_NOTNULL(second.apply_status_effect(/datum/status_effect/gnoll_bond, first, pack), "The bond should apply to the second partner.")

	bond.tick()
	TEST_ASSERT_NOTNULL(first.has_status_effect(/datum/status_effect/gnoll_bond), "Partners side by side should stay bonded.")

	second.moveToNullspace()
	bond.tick()
	TEST_ASSERT_NULL(first.has_status_effect(/datum/status_effect/gnoll_bond), "An escaped partner should break the bond.")
	TEST_ASSERT_NULL(second.has_status_effect(/datum/status_effect/gnoll_bond), "The bond should end for both partners.")

/datum/unit_test/gnoll_provision_values/Run()
	var/datum/contract_goal/gnoll/provisions/goal = allocate(/datum/contract_goal/gnoll/provisions)
	TEST_ASSERT_EQUAL(goal.get_offering_value(allocate(/obj/item/reagent_containers/food/snacks/meat/steak)), 1, "Raw meat should be worth 1.")
	TEST_ASSERT_EQUAL(goal.get_offering_value(allocate(/obj/item/reagent_containers/food/snacks/bread)), 2, "Plain cooked food should be worth 2.")
	TEST_ASSERT_EQUAL(goal.get_offering_value(allocate(/obj/item/reagent_containers/food/snacks/pieslice/good)), 3, "A hearty dish should be worth 3.")

/datum/unit_test/gnoll_favor_is_capped/Run()
	var/datum/team/gnoll/pack = allocate(/datum/team/gnoll)
	var/datum/contract_party/party = pack.contract_party
	TEST_ASSERT_NOTNULL(party, "A pack should own a contract party.")
	var/base_limit = pack.get_member_limit()
	party.adjust_favor(10)
	TEST_ASSERT_EQUAL(party.favor, party.contract_pool.max_favor, "Favor should stop at the pool's maximum.")
	TEST_ASSERT(party.favor > 0, "The gnoll pool should allow favor.")
	TEST_ASSERT_EQUAL(pack.get_member_limit(), base_limit + 1, "Renewal favor should allow one more champion.")
	party.adjust_favor(-10)
	TEST_ASSERT_EQUAL(party.favor, 0, "Favor should never drop below zero.")
	TEST_ASSERT_EQUAL(pack.get_member_limit(), base_limit, "Without favor the pack keeps its normal limit.")

	var/datum/contract_party/plain_party = allocate(/datum/contract_party, /datum/contract_pool/werewolf, FALSE)
	plain_party.adjust_favor(3)
	TEST_ASSERT_EQUAL(plain_party.favor, 0, "Pools without a favor maximum should never gain favor.")

/datum/unit_test/gnoll_swift_path_halves_blood_cost/Run()
	var/datum/team/gnoll/pack = allocate(/datum/team/gnoll)
	var/datum/antagonist/gnoll/hunter = allocate(/datum/antagonist/gnoll)
	hunter.pack = pack
	var/full_cost = get_gnoll_abduct_blood_cost(hunter)
	TEST_ASSERT(full_cost > 0, "Abduct should cost blood without favor.")
	pack.contract_party.adjust_favor(1)
	TEST_ASSERT_EQUAL(get_gnoll_abduct_blood_cost(hunter), full_cost, "Keen Trail alone should not cut the blood cost.")
	pack.contract_party.adjust_favor(1)
	TEST_ASSERT_EQUAL(get_gnoll_abduct_blood_cost(hunter), round(full_cost / 2), "Swift Path should halve the blood cost.")
	hunter.pack = null

/datum/unit_test/gnoll_goal_pays_boon_and_gift/Run()
	var/datum/team/gnoll/pack = allocate(/datum/team/gnoll)
	var/obj/structure/gnoll_shrine/shrine = allocate(/obj/structure/gnoll_shrine)
	var/list/before = list()
	for(var/obj/item/thing in range(1, shrine))
		before += thing
	pack.on_goal_fulfilled(null)
	TEST_ASSERT_EQUAL(pack.boon_charges, 1, "A fulfilled goal should grant one boon charge.")
	var/list/gifts = list()
	for(var/obj/item/thing in range(1, shrine))
		if(!(thing in before))
			gifts += thing
	TEST_ASSERT(length(gifts), "A fulfilled goal should leave a gift beside the shrine.")
	QDEL_LIST(gifts)

/datum/unit_test/gnoll_virility_fades_after_conception/Run()
	var/datum/team/gnoll/pack = allocate(/datum/team/gnoll)
	var/mob/living/carbon/human/carrier = make_gnoll_test_carrier(src)
	var/mob/living/carbon/human/father = allocate(/mob/living/carbon/human)
	for(var/slot in list(ORGAN_SLOT_PENIS, ORGAN_SLOT_TESTICLES))
		for(var/obj/item/organ/genitals/organ as anything in father.getorganslotlist(slot))
			father.remove_gender_potion_genital_organ(organ)
	TEST_ASSERT_NULL(father.getorganslot(ORGAN_SLOT_PENIS), "The test father should start without a penis.")

	var/datum/status_effect/temporary_futanari/virility = father.apply_status_effect(/datum/status_effect/temporary_futanari, 15 MINUTES)
	TEST_ASSERT_NOTNULL(virility, "The blessing should apply to a body without male anatomy.")
	TEST_ASSERT_NOTNULL(get_real_organ(father, ORGAN_SLOT_PENIS), "The blessing should grow a real penis.")
	TEST_ASSERT_NOTNULL(father.getorganslot(ORGAN_SLOT_TESTICLES), "The blessing should grow testicles.")
	virility.tick()
	TEST_ASSERT_NOTNULL(father.has_status_effect(/datum/status_effect/temporary_futanari), "The blessing should last until it expires or is spent.")

	var/datum/status_effect/gnoll_fertility_mark/mark = carrier.apply_status_effect(/datum/status_effect/gnoll_fertility_mark, pack)
	TEST_ASSERT(mark.conceive(father), "A blessed champion should be able to conceive.")
	TEST_ASSERT(virility.dissipating, "Conception should spend the blessing.")
	virility.tick()
	TEST_ASSERT_NULL(father.has_status_effect(/datum/status_effect/temporary_futanari), "A spent blessing should fade outside a scene.")
	TEST_ASSERT_NULL(father.getorganslot(ORGAN_SLOT_PENIS), "The borrowed penis should be gone.")
	TEST_ASSERT_NULL(father.getorganslot(ORGAN_SLOT_TESTICLES), "The borrowed testicles should be gone.")

/datum/unit_test/gnoll_contract_lines_reach_memories/Run()
	var/mob/living/carbon/human/body = allocate(/mob/living/carbon/human)
	body.mind_initialize()
	var/datum/antagonist/gnoll/champion = body.mind.add_antag_datum(/datum/antagonist/gnoll)
	TEST_ASSERT_NOTNULL(champion, "The test body should become a champion.")
	var/list/lines = body.mind.get_contract_demand_lines()
	TEST_ASSERT(length(lines), "A champion should have contract lines to review.")
	var/joined = jointext(lines, "\n")
	TEST_ASSERT(findtext(joined, "Gorellik"), "The lines should name the pack's patron.")
	TEST_ASSERT(findtext(joined, "Favor of Gorellik: 0/"), "The lines should show the pack's favor.")
	var/datum/team/gnoll/pack = champion.pack
	body.mind.remove_antag_datum(/datum/antagonist/gnoll)
	qdel(pack)

/datum/unit_test/gnoll_hunt_accepts_yield_and_binding/Run()
	var/mob/living/carbon/human/body = allocate(/mob/living/carbon/human)
	body.mind_initialize()
	var/datum/antagonist/gnoll/champion = body.mind.add_antag_datum(/datum/antagonist/gnoll)
	TEST_ASSERT_NOTNULL(champion, "The test body should become a champion.")
	var/datum/antag_contract/contract = champion.pack.contract_party.current_contract
	TEST_ASSERT_NOTNULL(contract, "The pack should hold a contract.")
	var/datum/contract_goal/gnoll/hunt/hunt = new(champion)
	contract.goals += hunt
	var/mob/living/carbon/human/quarry = allocate(/mob/living/carbon/human)

	hunt.track_quarry(quarry)
	SEND_SIGNAL(quarry, COMSIG_LIVING_YIELDED)
	TEST_ASSERT(hunt.downed_by_pack && hunt.recovered, "Yielding beside a packmate should subdue the quarry.")

	hunt.track_quarry(quarry)
	ADD_TRAIT(quarry, TRAIT_RESTRAINED, TRAIT_GENERIC)
	TEST_ASSERT_NOTNULL(hunt.bound_timer, "Binding the quarry should start the hold timer.")
	REMOVE_TRAIT(quarry, TRAIT_RESTRAINED, TRAIT_GENERIC)
	TEST_ASSERT_NULL(hunt.bound_timer, "Freeing the quarry should cancel the hold timer.")
	ADD_TRAIT(quarry, TRAIT_RESTRAINED, TRAIT_GENERIC)
	hunt.check_still_bound()
	TEST_ASSERT(hunt.downed_by_pack && hunt.recovered, "A quarry held bound near a packmate should be subdued.")
	REMOVE_TRAIT(quarry, TRAIT_RESTRAINED, TRAIT_GENERIC)

	hunt.track_quarry(quarry)
	body.moveToNullspace()
	SEND_SIGNAL(quarry, COMSIG_LIVING_YIELDED)
	TEST_ASSERT(!hunt.downed_by_pack, "A yield with no packmate near should not count.")

	contract.goals -= hunt
	qdel(hunt)
	var/datum/team/gnoll/pack = champion.pack
	body.mind.remove_antag_datum(/datum/antagonist/gnoll)
	qdel(pack)

/datum/unit_test/gnoll_hunter_carries_capture_gear/Run()
	var/mob/living/carbon/human/body = allocate(/mob/living/carbon/human)
	body.mind_initialize()
	var/datum/antagonist/gnoll/champion = body.mind.add_antag_datum(/datum/antagonist/gnoll)
	TEST_ASSERT_NOTNULL(champion, "The test body should become a champion.")
	body.equipOutfit(/datum/outfit/gnoll/hunter)
	var/bolas = 0
	var/ropes = 0
	for(var/obj/item/rope/item in body.get_all_contents())
		if(istype(item, /obj/item/rope/net/bola))
			bolas++
		else if(item.type == /obj/item/rope)
			ropes++
	TEST_ASSERT_EQUAL(bolas, 2, "A gnoll hunter should carry two bolas.")
	TEST_ASSERT_EQUAL(ropes, 2, "A gnoll hunter should carry two ropes.")
	var/list/dropped = list()
	for(var/obj/item/rope/item in get_turf(body))
		dropped += item
	TEST_ASSERT(!length(dropped), "No capture gear should fall to the floor.")
	var/datum/team/gnoll/pack = champion.pack
	body.mind.remove_antag_datum(/datum/antagonist/gnoll)
	qdel(pack)
