/datum/unit_test/blindfolds_block_sight/Run()
	var/mob/living/carbon/human/wearer = allocate(/mob/living/carbon/human)
	var/obj/item/clothing/face/blindfold/blindfold = allocate(/obj/item/clothing/face/blindfold)
	TEST_ASSERT(wearer.equip_to_slot_if_possible(blindfold, ITEM_SLOT_MASK, disable_warning = TRUE), "The blindfold should tie on.")
	TEST_ASSERT(wearer.is_blind(), "A blindfold should blind its wearer.")
	wearer.put_in_hands(blindfold)
	TEST_ASSERT(!wearer.is_blind(), "A blindfold held in the hand should not blind.")
	wearer.dropItemToGround(blindfold)
	var/obj/item/clothing/face/blindfold/sheer/sheer = allocate(/obj/item/clothing/face/blindfold/sheer)
	TEST_ASSERT_EQUAL(sheer.icon_state, blindfold.icon_state, "A sheer blindfold should look like a plain one.")
	wearer.equip_to_slot_if_possible(sheer, ITEM_SLOT_MASK, disable_warning = TRUE)
	TEST_ASSERT(!wearer.is_blind(), "A sheer blindfold should let its wearer see.")

/datum/unit_test/strapon_drop_keeps_real_cocks/Run()
	var/mob/living/carbon/human/wearer = allocate(/mob/living/carbon/human)
	var/obj/item/dildo/toy = allocate(/obj/item/dildo)
	toy.update_strapon()
	TEST_ASSERT(wearer.equip_to_slot_if_possible(toy, ITEM_SLOT_BELT, disable_warning = TRUE), "The strapon should buckle on.")
	TEST_ASSERT_EQUAL(wearer.getorganslot(ORGAN_SLOT_PENIS), toy.strapon, "A buckled strapon should give its wearer a cock.")
	wearer.dropItemToGround(toy)
	TEST_ASSERT_NULL(wearer.getorganslot(ORGAN_SLOT_PENIS), "Unbuckling should take the strapon cock away.")
	TEST_ASSERT_NULL(toy.wearer, "A dropped strapon should forget its wearer.")
	var/obj/item/organ/genitals/penis/real = allocate(/obj/item/organ/genitals/penis)
	real.Insert(wearer, TRUE, FALSE)
	wearer.put_in_hands(toy)
	wearer.dropItemToGround(toy)
	TEST_ASSERT_EQUAL(wearer.getorganslot(ORGAN_SLOT_PENIS), real, "Dropping the toy later should leave a real cock alone.")

/datum/unit_test/playthings_sprites_exist/Run()
	for(var/state in list("riding_crop", "paddle", "flogger", "nipple_clamps", "shibari"))
		TEST_ASSERT(icon_exists('modular_rmh/icons/obj/lewd/playthings.dmi', state), "Missing plaything icon state [state].")
	for(var/size in 1 to 5)
		TEST_ASSERT(icon_exists('modular_rmh/icons/mob/sprite_accessory/nipple_clamps.dmi', "clamps-[size]"), "Missing worn clamps for breast size [size].")

/datum/unit_test/impact_toys_sting_without_wounds/Run()
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human)
	var/mob/living/carbon/human/target = allocate(/mob/living/carbon/human)
	var/obj/item/impact_toy/paddle/paddle = allocate(/obj/item/impact_toy/paddle)
	user.put_in_active_hand(paddle)
	user.zone_selected = BODY_ZONE_PRECISE_GROIN
	var/datum/sex_scene_controller/controller = user.open_sex_scene(target, FALSE)
	var/datum/sex_action/impact_play/action = controller.instantiate_action(/datum/sex_action/impact_play)
	TEST_ASSERT(action.bind_runtime(controller), "Impact play should bind to the scene.")
	TEST_ASSERT_EQUAL(action.action_item, paddle, "Impact play should pick up the held paddle.")
	TEST_ASSERT(action.shows_on_menu(user, target), "A held paddle should offer impact play.")
	TEST_ASSERT(action.can_perform(user, target), "A bare rear should take the paddle.")
	var/list/arousal_before = list()
	SEND_SIGNAL(target, COMSIG_SEX_GET_AROUSAL, arousal_before)
	var/runtimed = FALSE
	try
		action.on_perform(user, target)
	catch
		runtimed = TRUE
	var/list/arousal_after = list()
	SEND_SIGNAL(target, COMSIG_SEX_GET_AROUSAL, arousal_after)
	action.selected_zone = BODY_ZONE_HEAD
	var/reaches_head = action.can_perform(user, target)
	user.sex_scene?.stop_action(action)
	qdel(controller)
	TEST_ASSERT(!runtimed, "A paddle strike should not runtime.")
	TEST_ASSERT(arousal_after["arousal"] > arousal_before["arousal"], "A paddle strike should arouse.")
	TEST_ASSERT_EQUAL(target.getBruteLoss(), 0, "A paddle strike should never wound.")
	TEST_ASSERT(!reaches_head, "Impact play should not reach the head.")

/datum/unit_test/tail_plug_grows_a_false_tail/Run()
	var/mob/living/carbon/human/wearer = allocate(/mob/living/carbon/human)
	var/obj/item/organ/genitals/filling_organ/anus/anus = allocate(/obj/item/organ/genitals/filling_organ/anus)
	anus.Insert(wearer, TRUE, FALSE)
	var/obj/item/dildo/plug/tail/plug = allocate(/obj/item/dildo/plug/tail)
	SEND_SIGNAL(anus, COMSIG_BODYSTORAGE_FORCE_INSERT, plug, STORAGE_LAYER_INNER)
	var/obj/item/organ/tail/worn_tail = wearer.getorganslot(ORGAN_SLOT_TAIL)
	TEST_ASSERT(istype(worn_tail, /obj/item/organ/tail/false_tail), "A worn tail plug should grow a false tail.")
	TEST_ASSERT_EQUAL(worn_tail?.accessory_type, plug.tail_accessory, "The false tail should copy the chosen tail sprite.")
	TEST_ASSERT(length(worn_tail?.get_bodypart_overlay(wearer.get_bodypart(BODY_ZONE_CHEST))), "The false tail should draw like a real one.")
	TEST_ASSERT_NULL(get_real_organ(wearer, ORGAN_SLOT_TAIL), "A false tail is not a real one.")
	wearer.update_organ_colors()
	TEST_ASSERT_EQUAL(worn_tail?.accessory_colors, plug.get_tail_colors(), "The false tail should keep the plug's fur colour.")
	var/mob/living/carbon/human/partner = allocate(/mob/living/carbon/human)
	var/obj/item/organ/genitals/penis/cock = allocate(/obj/item/organ/genitals/penis)
	cock.Insert(partner, TRUE, FALSE)
	var/datum/sex_action/tailjob/penis/tailjob = allocate(/datum/sex_action/tailjob/penis)
	TEST_ASSERT(!tailjob.shows_on_menu(wearer, partner), "A false tail should not tease like a real one.")
	fit_chastity_test_device(partner, /obj/item/clothing/undies/chastity/cage)
	var/datum/sex_action/chastity/tail/cage/tail_prod = allocate(/datum/sex_action/chastity/tail/cage)
	TEST_ASSERT(!tail_prod.shows_on_menu(wearer, partner), "A false tail should not prod a cage.")
	SEND_SIGNAL(anus, COMSIG_BODYSTORAGE_FORCE_REMOVE, plug, STORAGE_LAYER_INNER)
	TEST_ASSERT_NULL(wearer.getorganslot(ORGAN_SLOT_TAIL), "Taking the plug out should take the false tail too.")
	TEST_ASSERT_NULL(plug.false_tail, "The plug should forget its false tail.")

	var/obj/item/organ/tail/cat/real_tail = allocate(/obj/item/organ/tail/cat)
	real_tail.Insert(wearer, TRUE, FALSE)
	SEND_SIGNAL(anus, COMSIG_BODYSTORAGE_FORCE_INSERT, plug, STORAGE_LAYER_INNER)
	TEST_ASSERT_EQUAL(wearer.getorganslot(ORGAN_SLOT_TAIL), real_tail, "A real tail should stay in place.")
	SEND_SIGNAL(anus, COMSIG_BODYSTORAGE_FORCE_REMOVE, plug, STORAGE_LAYER_INNER)
	TEST_ASSERT_EQUAL(wearer.getorganslot(ORGAN_SLOT_TAIL), real_tail, "Taking the plug out should leave a real tail alone.")

/datum/unit_test/nipple_clamps_bite_and_come_off/Run()
	var/mob/living/carbon/human/wearer = allocate(/mob/living/carbon/human)
	var/mob/living/carbon/human/partner = allocate(/mob/living/carbon/human)
	var/obj/item/nipple_clamps/clamps = allocate(/obj/item/nipple_clamps)
	var/datum/sex_action/nipple_clamps/tug/tug = allocate(/datum/sex_action/nipple_clamps/tug)
	TEST_ASSERT(!tug.shows_on_menu(partner, wearer), "Bare nipples have no chain to tug.")
	TEST_ASSERT(clamps.clamp_onto(wearer), "Clamps should fit a bare chest.")
	TEST_ASSERT_EQUAL(wearer.nipple_clamps, clamps, "The wearer should know their clamps.")
	TEST_ASSERT(wearer.has_status_effect(/datum/status_effect/nipple_clamps), "Worn clamps should keep biting.")
	TEST_ASSERT_NOTNULL(wearer.get_bodypart_feature_of_slot("nipple_clamps"), "Worn clamps should draw on the chest.")
	TEST_ASSERT(tug.shows_on_menu(partner, wearer), "Worn clamps should offer tugging the chain.")
	TEST_ASSERT(tug.can_perform(partner, wearer), "A partner should reach a bare clamped chest.")
	TEST_ASSERT(!tug.shows_on_menu(wearer, wearer), "Tugging the chain is a partner action.")
	var/obj/item/nipple_clamps/second_pair = allocate(/obj/item/nipple_clamps)
	TEST_ASSERT(!second_pair.clamp_onto(wearer), "Only one pair of clamps should fit.")
	TEST_ASSERT(clamps.unclamp(wearer, partner), "A partner should take the clamps off.")
	TEST_ASSERT_NULL(wearer.nipple_clamps, "Removed clamps should leave the wearer.")
	TEST_ASSERT(!wearer.has_status_effect(/datum/status_effect/nipple_clamps), "Removed clamps should stop biting.")
	TEST_ASSERT_NULL(wearer.get_bodypart_feature_of_slot("nipple_clamps"), "Removed clamps should stop drawing.")
	TEST_ASSERT(partner.is_holding(clamps), "Removed clamps should land in the remover's hand.")

/// Each plaything recipe starts from the items a player really holds and clicks with.
/datum/unit_test/playthings_recipes_can_start/Run()
	var/mob/living/carbon/human/crafter = allocate(/mob/living/carbon/human)
	// Recipe = list(held item, clicked item, other ingredients...).
	var/list/cases = list(
		/datum/repeatable_crafting_recipe/sewing/blindfold = list(/obj/item/needle, /obj/item/natural/cloth),
		/datum/repeatable_crafting_recipe/leather/impact_toy/riding_crop = list(/obj/item/needle, /obj/item/natural/hide/cured, /obj/item/grown/log/tree/stick),
		/datum/repeatable_crafting_recipe/leather/impact_toy/paddle = list(/obj/item/needle, /obj/item/natural/hide/cured, /obj/item/natural/wood/plank),
		/datum/repeatable_crafting_recipe/leather/impact_toy/flogger = list(/obj/item/needle, /obj/item/natural/hide/cured, /obj/item/natural/hide/cured, /obj/item/grown/log/tree/stick),
		/datum/repeatable_crafting_recipe/crafting/tail_plug = list(/obj/item/natural/fur, /obj/item/dildo/plug/wood),
		/datum/repeatable_crafting_recipe/crafting/shibari = list(/obj/item/natural/fibers, /obj/item/rope, /obj/item/natural/fibers),
		/datum/repeatable_crafting_recipe/crafting/anal_beads_wood = list(/obj/item/weapon/knife/hunting, /obj/item/grown/log/tree/small, /obj/item/natural/fibers),
		/datum/repeatable_crafting_recipe/crafting/anal_beads_stone = list(/obj/item/weapon/knife/hunting, /obj/item/natural/stone, /obj/item/natural/fibers),
	)
	for(var/recipe_type in cases)
		var/list/items = list()
		for(var/item_type in cases[recipe_type])
			items += allocate(item_type)
		var/obj/item/held = items[1]
		var/obj/item/clicked = items[2]
		crafter.put_in_active_hand(held)
		var/found = FALSE
		for(var/datum/repeatable_crafting_recipe/recipe as anything in crafter.try_repeatable_craft(clicked, held))
			if(recipe.type == recipe_type)
				found = TRUE
		TEST_ASSERT(found, "[recipe_type] should start from [held] used on [clicked].")
		for(var/obj/item/item as anything in items)
			qdel(item)
