/datum/unit_test/swingdelay_status_blocks_swinging_check/Run()
	var/mob/living/carbon/human/dummy = allocate(/mob/living/carbon/human)
	TEST_ASSERT(!dummy.is_swinging(), "Fresh mob should not be swinging")
	dummy.apply_status_effect(/datum/status_effect/swingdelay, 10)
	TEST_ASSERT(dummy.is_swinging(), "Mob with swingdelay effect should report swinging")
	TEST_ASSERT(dummy.swing_state, "swingdelay on_apply must set swing_state")

/datum/unit_test/swingdelay_disrupt_cancelled_by_attack/Run()
	var/mob/living/carbon/human/dummy = allocate(/mob/living/carbon/human)
	var/mob/living/carbon/human/attacker = allocate(/mob/living/carbon/human)
	dummy.apply_status_effect(/datum/status_effect/swingdelay/disrupt, 10)
	TEST_ASSERT(dummy.swing_state, "Disrupt swing starts with swing_state TRUE")
	dummy.checkdefense(null, attacker)
	TEST_ASSERT(!dummy.swing_state, "Being attacked during a disruptable swing must clear swing_state")
	var/datum/status_effect/swingdelay/disrupt/SW = dummy.has_status_effect(/datum/status_effect/swingdelay/disrupt)
	TEST_ASSERT(SW?.is_disrupted, "Disrupt effect must be flagged disrupted after being struck")

/datum/unit_test/swingdelay_normal_swing_not_cancelled_by_attack/Run()
	var/mob/living/carbon/human/dummy = allocate(/mob/living/carbon/human)
	var/mob/living/carbon/human/attacker = allocate(/mob/living/carbon/human)
	dummy.apply_status_effect(/datum/status_effect/swingdelay, 10)
	dummy.checkdefense(null, attacker)
	TEST_ASSERT(dummy.swing_state, "A NORMAL swing must not be cancelled by being attacked")

/datum/unit_test/swingdelay_disrupt_tail_does_not_eat_defense/Run()
	var/mob/living/carbon/human/dummy = allocate(/mob/living/carbon/human)
	var/mob/living/carbon/human/attacker = allocate(/mob/living/carbon/human)
	dummy.apply_status_effect(/datum/status_effect/swingdelay/disrupt, 10)
	dummy.swing_state = FALSE // simulate: swing already resolved, effect in its 2-tick tail
	dummy.checkdefense(null, attacker)
	var/datum/status_effect/swingdelay/disrupt/SW = dummy.has_status_effect(/datum/status_effect/swingdelay/disrupt)
	TEST_ASSERT(!SW.is_disrupted, "A hit during the post-swing effect tail must not consume the disruption")
