/datum/unit_test/tempo_stacks_apply_buffs/Run()
	var/mob/living/carbon/human/dummy = allocate(/mob/living/carbon/human)
	ADD_TRAIT(dummy, TRAIT_TEMPO, TRAIT_GENERIC)
	dummy.tempo_attackers = list("ref1" = world.time + 30 SECONDS, "ref2" = world.time + 30 SECONDS)
	dummy.manage_tempo()
	TEST_ASSERT(dummy.has_status_effect(/datum/status_effect/buff/tempo_one), "2 attackers = tempo one")
	dummy.tempo_attackers["ref3"] = world.time + 30 SECONDS
	dummy.tempo_attackers["ref4"] = world.time + 30 SECONDS
	dummy.manage_tempo()
	TEST_ASSERT(dummy.has_status_effect(/datum/status_effect/buff/tempo_three), "4 attackers = tempo three")
	TEST_ASSERT(!dummy.has_status_effect(/datum/status_effect/buff/tempo_one), "tempo tiers are exclusive")

/datum/unit_test/tempo_bonus_lookup/Run()
	var/mob/living/carbon/human/dummy = allocate(/mob/living/carbon/human)
	TEST_ASSERT_EQUAL(dummy.get_tempo_bonus(TEMPO_TAG_PARRYCD_BONUS), 0, "No tempo = no bonus")
	TEST_ASSERT_EQUAL(dummy.get_tempo_bonus(TEMPO_TAG_ARMOR_INTEGFACTOR), 1, "No tempo = neutral integrity factor")
	dummy.apply_status_effect(/datum/status_effect/buff/tempo_two)
	TEST_ASSERT_EQUAL(dummy.get_tempo_bonus(TEMPO_TAG_PARRYCD_BONUS), 4, "Tempo two = 4 ds parry CDR")
	TEST_ASSERT_EQUAL(dummy.get_tempo_bonus(TEMPO_TAG_STAMLOSS_DODGE), 5, "Tempo two = 5 less dodge stamina")

/datum/unit_test/tempo_cull_drops_stale_attackers/Run()
	var/mob/living/carbon/human/dummy = allocate(/mob/living/carbon/human)
	ADD_TRAIT(dummy, TRAIT_TEMPO, TRAIT_GENERIC)
	dummy.tempo_attackers = list("stale" = world.time - 1, "fresh" = world.time + 30 SECONDS, "fresh2" = world.time + 30 SECONDS)
	dummy.cull_tempo_list()
	TEST_ASSERT_EQUAL(length(dummy.tempo_attackers), 2, "Cull must drop expired attackers")
	TEST_ASSERT(dummy.has_status_effect(/datum/status_effect/buff/tempo_one), "2 fresh attackers = tempo one after cull")

/datum/unit_test/tempo_stale_attackers_dont_inflate/Run()
	var/mob/living/carbon/human/dummy = allocate(/mob/living/carbon/human)
	var/mob/living/carbon/human/attacker = allocate(/mob/living/carbon/human)
	attacker.mind_initialize()
	ADD_TRAIT(dummy, TRAIT_TEMPO, TRAIT_GENERIC)
	// two stale entries from a long-finished fight
	dummy.tempo_attackers = list("stale1" = world.time - 1, "stale2" = world.time - 1)
	dummy.process_tempo_attack(attacker)
	TEST_ASSERT_EQUAL(length(dummy.tempo_attackers), 1, "Stale entries must be pruned before counting a new attacker")
	TEST_ASSERT(!dummy.has_status_effect(/datum/status_effect/buff/tempo_one), "One real attacker must not grant tempo")

/datum/unit_test/tempo_attacker_cap/Run()
	var/mob/living/carbon/human/dummy = allocate(/mob/living/carbon/human)
	var/mob/living/carbon/human/attacker = allocate(/mob/living/carbon/human)
	attacker.mind_initialize()
	ADD_TRAIT(dummy, TRAIT_TEMPO, TRAIT_GENERIC)
	for(var/i in 1 to TEMPO_CAP)
		dummy.tempo_attackers["ref[i]"] = world.time + 30 SECONDS
	dummy.process_tempo_attack(attacker)
	TEST_ASSERT_EQUAL(length(dummy.tempo_attackers), TEMPO_CAP, "Attacker list must not grow beyond TEMPO_CAP")
