// Ported ERP module entrypoint for Rivermist.
// Intentionally excludes source patches that collide with the legacy stack:
// - patches/arousal.dm
// - patches/flaw.dm
// - patches/mob.dm
// - patches/organs.dm
// - core/erp_kink.dm
// - additionals/erp_emotes.dm
// - additionals/erp_items.dm
// - additionals/erp_modifiers.dm
// - additionals/erp_reagents.dm
// - additionals/erp_stress_effects.dm

#include "_defines.dm"

#include "bridges\erp_shims.dm"

#include "components\erp_kinks.dm"
#include "components\erp_knot.dm"
#include "components\erp_relations.dm"

#include "organs\erp_liquid_storage.dm"
#include "organs\erp_organ_inject_router.dm"
#include "organs\erp_organ_prefs_service.dm"
#include "organs\erp_organ_spill_policy.dm"
#include "organs\_erp_sex_organ.dm"
#include "organs\types\anus.dm"
#include "organs\types\breasts.dm"
#include "organs\types\limbs.dm"
#include "organs\types\mouth.dm"
#include "organs\types\penis.dm"
#include "organs\types\vagina.dm"

#include "actions\erp_action_core.dm"
#include "actions\erp_action_editor_schema.dm"
#include "actions\erp_action_message_renderer.dm"
#include "actions\erp_action_prefs_codec.dm"
#include "actions\interaction\_other.dm"
#include "actions\interaction\anus\butt.dm"
#include "actions\interaction\anus\face.dm"
#include "actions\interaction\anus\force_face.dm"
#include "actions\interaction\anus\rubbing.dm"
#include "actions\interaction\anus\sex.dm"
#include "actions\interaction\anus\tail.dm"
#include "actions\interaction\anus\_anus.dm"
#include "actions\interaction\body\grinding.dm"
#include "actions\interaction\body\rubbing.dm"
#include "actions\interaction\body\_body.dm"
#include "actions\interaction\breasts\breast_feed.dm"
#include "actions\interaction\breasts\teasing.dm"
#include "actions\interaction\breasts\titjob.dm"
#include "actions\interaction\breasts\_breasts.dm"
#include "actions\interaction\hands\breasts_play.dm"
#include "actions\interaction\hands\finger_anal.dm"
#include "actions\interaction\hands\finger_oral.dm"
#include "actions\interaction\hands\finger_vaginal.dm"
#include "actions\interaction\hands\force_armpits.dm"
#include "actions\interaction\hands\masturbation.dm"
#include "actions\interaction\hands\milking_breasts.dm"
#include "actions\interaction\hands\milking_penis.dm"
#include "actions\interaction\hands\rubbing.dm"
#include "actions\interaction\hands\sextoy_anal.dm"
#include "actions\interaction\hands\sextoy_oral.dm"
#include "actions\interaction\hands\sextoy_vaginal.dm"
#include "actions\interaction\hands\spanking.dm"
#include "actions\interaction\hands\tease_tail.dm"
#include "actions\interaction\hands\tease_testicles.dm"
#include "actions\interaction\hands\tease_vagina.dm"
#include "actions\interaction\hands\_hands.dm"
#include "actions\interaction\legs\footfetish.dm"
#include "actions\interaction\legs\footjob.dm"
#include "actions\interaction\legs\legsjob.dm"
#include "actions\interaction\legs\teasing.dm"
#include "actions\interaction\legs\_legs.dm"
#include "actions\interaction\mouth\blowjob.dm"
#include "actions\interaction\mouth\breast_feed.dm"
#include "actions\interaction\mouth\cunnilingus.dm"
#include "actions\interaction\mouth\finger_lick.dm"
#include "actions\interaction\mouth\foot_lick.dm"
#include "actions\interaction\mouth\kiss.dm"
#include "actions\interaction\mouth\rimming.dm"
#include "actions\interaction\mouth\_mouth.dm"
#include "actions\interaction\penis\anal_sex.dm"
#include "actions\interaction\penis\butt_job.dm"
#include "actions\interaction\penis\force_blowjob.dm"
#include "actions\interaction\penis\masturbation.dm"
#include "actions\interaction\penis\oral_sex.dm"
#include "actions\interaction\penis\rubbing.dm"
#include "actions\interaction\penis\sword_fight.dm"
#include "actions\interaction\penis\tea_bag.dm"
#include "actions\interaction\penis\tit_job.dm"
#include "actions\interaction\penis\vaginal_sex.dm"
#include "actions\interaction\penis\_penis.dm"
#include "actions\interaction\tail\anal.dm"
#include "actions\interaction\tail\oral.dm"
#include "actions\interaction\tail\penis.dm"
#include "actions\interaction\tail\rubbing.dm"
#include "actions\interaction\tail\spanking.dm"
#include "actions\interaction\tail\squeeze_breasts.dm"
#include "actions\interaction\tail\vaginal.dm"
#include "actions\interaction\tail\_tail.dm"
#include "actions\interaction\vagina\face.dm"
#include "actions\interaction\vagina\force_face.dm"
#include "actions\interaction\vagina\masturbation.dm"
#include "actions\interaction\vagina\rubbing.dm"
#include "actions\interaction\vagina\scissors.dm"
#include "actions\interaction\vagina\sex.dm"
#include "actions\interaction\vagina\tail.dm"
#include "actions\interaction\vagina\_vagina.dm"
#include "actions\masturbation\_self.dm"
#include "actions\masturbation\hands\breasts_milking.dm"
#include "actions\masturbation\hands\breasts_play.dm"
#include "actions\masturbation\hands\fingering_anal.dm"
#include "actions\masturbation\hands\fingering_oral.dm"
#include "actions\masturbation\hands\fingering_vaginal.dm"
#include "actions\masturbation\hands\penis.dm"
#include "actions\masturbation\hands\penis_milking.dm"
#include "actions\masturbation\hands\sextoy_anal.dm"
#include "actions\masturbation\hands\sextoy_oral.dm"
#include "actions\masturbation\hands\sextoy_vaginal.dm"
#include "actions\masturbation\hands\tail_play.dm"
#include "actions\masturbation\hands\teasing_clitoris.dm"
#include "actions\masturbation\hands\_hands.dm"
#include "actions\masturbation\tail\anal.dm"
#include "actions\masturbation\tail\breasts.dm"
#include "actions\masturbation\tail\oral.dm"
#include "actions\masturbation\tail\penis.dm"
#include "actions\masturbation\tail\vaginal.dm"
#include "actions\masturbation\tail\_tail.dm"

#include "actor\erp_actor.dm"
#include "actor\erp_actor_custom_actions_service.dm"
#include "actor\erp_actor_ui_helpers.dm"
#include "actor\erp_dullahan_head.dm"
#include "actor\erp_human.dm"
#include "actor\erp_mob.dm"
#include "actor\erp_object.dm"

#include "additionals\erp_decals.dm"
#include "additionals\erp_status_effects.dm"

#include "core\erp_catalog.dm"
#include "core\erp_factory.dm"
#include "core\erp_resolver.dm"
#include "core\link\erp_link.dm"
#include "core\link\erp_link_math.dm"
#include "core\link\erp_link_presenter.dm"
#include "core\link\erp_link_rules.dm"
#include "core\knot\erp_knot_effects.dm"
#include "core\knot\erp_knot_link.dm"
#include "core\knot\erp_knot_policy.dm"
#include "core\knot\erp_knot_rules.dm"
#include "core\knot\erp_knot_service.dm"
#include "core\scene\erp_scene_effects.dm"
#include "core\scene\erp_scene_messaging.dm"
#include "core\scene\erp_scene_runtime.dm"
#include "core\services\erp_climax_service.dm"
#include "core\services\erp_injection_service.dm"
#include "core\services\erp_vfx_service.dm"

#include "ui\erp_sex_ui_tab.dm"
#include "ui\erp_sex_ui_actions.dm"
#include "ui\erp_sex_ui_editor.dm"
#include "ui\erp_sex_ui_kinks.dm"
#include "ui\erp_sex_ui_status.dm"
#include "ui\erp_sex_ui.dm"

#include "core\controller\erp_controller_actions.dm"
#include "core\controller\erp_controller_context.dm"
#include "core\controller\erp_controller_kinks.dm"
#include "core\controller\erp_controller_links.dm"
#include "core\controller\erp_controller_organs.dm"
#include "core\controller\erp_controller_partners.dm"
#include "core\controller\erp_controller_ui.dm"
#include "core\controller\erp_controller.dm"
#include "core\erp_system.dm"

#include "patches\preferences.dm"

#include "bridges\erp_kink_bridge.dm"
#include "bridges\erp_mob.dm"
